function arrayConvert(value) {
    return {
        value: value.label,
        label: value.label,
    }
}
export const provinces = [
    { label: 'กรุงเทพมหานคร' },
    { label: 'สมุทรปราการ' },
    { label: 'นนทบุรี' },
    { label: 'ปทุมธานี' },
    { label: 'พระนครศรีอยุธยา' },
    { label: 'อ่างทอง' },
    { label: 'ลพบุรี' },
    { label: 'สิงห์บุรี' },
    { label: 'ชัยนาท' },
    { label: 'สระบุรี' },
    { label: 'ชลบุรี' },
    { label: 'ระยอง' },
    { label: 'จันทบุรี' },
    { label: 'ตราด' },
    { label: 'ฉะเชิงเทรา' },
    { label: 'ปราจีนบุรี' },
    { label: 'นครนายก' },
    { label: 'สระแก้ว' },
    { label: 'นครราชสีมา' },
    { label: 'บุรีรัมย์' },
    { label: 'สุรินทร์' },
    { label: 'ศรีสะเกษ' },
    { label: 'อุบลราชธานี' },
    { label: 'ยโสธร' },
    { label: 'ชัยภูมิ' },
    { label: 'อำนาจเจริญ' },
    { label: 'บึงกาฬ' },
    { label: 'หนองบัวลำภู' },
    { label: 'ขอนแก่น' },
    { label: 'อุดรธานี' },
    { label: 'เลย' },
    { label: 'หนองคาย' },
    { label: 'มหาสารคาม' },
    { label: 'ร้อยเอ็ด' },
    { label: 'กาฬสินธุ์' },
    { label: 'สกลนคร' },
    { label: 'นครพนม' },
    { label: 'มุกดาหาร' },
    { label: 'เชียงใหม่' },
    { label: 'ลำพูน' },
    { label: 'ลำปาง' },
    { label: 'อุตรดิตถ์' },
    { label: 'แพร่' },
    { label: 'น่าน' },
    { label: 'พะเยา' },
    { label: 'เชียงราย' },
    { label: 'แม่ฮ่องสอน' },
    { label: 'นครสวรรค์' },
    { label: 'อุทัยธานี' },
    { label: 'กำแพงเพชร' },
    { label: 'ตาก' },
    { label: 'สุโขทัย' },
    { label: 'พิษณุโลก' },
    { label: 'พิจิตร' },
    { label: 'เพชรบูรณ์' },
    { label: 'ราชบุรี' },
    { label: 'กาญจนบุรี' },
    { label: 'สุพรรณบุรี' },
    { label: 'นครปฐม' },
    { label: 'สมุทรสาคร' },
    { label: 'สมุทรสงคราม' },
    { label: 'เพชรบุรี' },
    { label: 'ประจวบคีรีขันธ์' },
    { label: 'นครศรีธรรมราช' },
    { label: 'กระบี่' },
    { label: 'พังงา' },
    { label: 'ภูเก็ต' },
    { label: 'สุราษฎร์ธานี' },
    { label: 'ระนอง' },
    { label: 'ชุมพร' },
    { label: 'สงขลา' },
    { label: 'สตูล' },
    { label: 'ตรัง' },
    { label: 'พัทลุง' },
    { label: 'ปัตตานี' },
    { label: 'ยะลา' },
    { label: 'นราธิวาส' },
]
    .map(province => arrayConvert(province))

export const amphoes = {
    กรุงเทพมหานคร: [
        { label: 'พระนคร' },
        { label: 'ดุสิต' },
        { label: 'หนองจอก' },
        { label: 'บางรัก' },
        { label: 'บางเขน' },
        { label: 'บางกะปิ' },
        { label: 'ปทุมวัน' },
        { label: 'ป้อมปราบศัตรูพ่าย' },
        { label: 'พระโขนง' },
        { label: 'มีนบุรี' },
        { label: 'ลาดกระบัง' },
        { label: 'ยานนาวา' },
        { label: 'สัมพันธวงศ์' },
        { label: 'พญาไท' },
        { label: 'ธนบุรี' },
        { label: 'บางกอกใหญ่' },
        { label: 'ห้วยขวาง' },
        { label: 'คลองสาน' },
        { label: 'ตลิ่งชัน' },
        { label: 'บางกอกน้อย' },
        { label: 'บางขุนเทียน' },
        { label: 'ภาษีเจริญ' },
        { label: 'หนองแขม' },
        { label: 'ราษฎร์บูรณะ' },
        { label: 'บางพลัด' },
        { label: 'ดินแดง' },
        { label: 'บึงกุ่ม' },
        { label: 'สาทร' },
        { label: 'บางซื่อ' },
        { label: 'จตุจักร' },
        { label: 'บางคอแหลม' },
        { label: 'ประเวศ' },
        { label: 'คลองเตย' },
        { label: 'สวนหลวง' },
        { label: 'จอมทอง' },
        { label: 'ดอนเมือง' },
        { label: 'ราชเทวี' },
        { label: 'ลาดพร้าว' },
        { label: 'วัฒนา' },
        { label: 'บางแค' },
        { label: 'หลักสี่' },
        { label: 'สายไหม' },
        { label: 'คันนายาว' },
        { label: 'สะพานสูง' },
        { label: 'วังทองหลาง' },
        { label: 'คลองสามวา' },
        { label: 'บางนา' },
        { label: 'ทวีวัฒนา' },
        { label: 'ทุ่งครุ' },
        { label: 'บางบอน' },
    ].map(amphoe => arrayConvert(amphoe)),

    สมุทรปราการ: [
        { label: 'เมืองสมุทรปราการ' },
        { label: 'บางบ่อ' },
        { label: 'บางพลี' },
        { label: 'พระประแดง' },
        { label: 'พระสมุทรเจดีย์' },
        { label: 'บางเสาธง' },
    ].map(amphoe => arrayConvert(amphoe)),

    นนทบุรี: [
        { label: 'เมืองนนทบุรี' },
        { label: 'บางกรวย' },
        { label: 'บางใหญ่' },
        { label: 'บางบัวทอง' },
        { label: 'ไทรน้อย' },
        { label: 'ปากเกร็ด' },
    ].map(amphoe => arrayConvert(amphoe)),

    ปทุมธานี: [
        { label: 'เมืองปทุมธานี' },
        { label: 'คลองหลวง' },
        { label: 'ธัญบุรี' },
        { label: 'หนองเสือ' },
        { label: 'ลาดหลุมแก้ว' },
        { label: 'ลำลูกกา' },
        { label: 'สามโคก' },
    ].map(amphoe => arrayConvert(amphoe)),

    พระนครศรีอยุธยา: [
        { label: 'พระนครศรีอยุธยา' },
        { label: 'ท่าเรือ' },
        { label: 'นครหลวง' },
        { label: 'บางไทร' },
        { label: 'บางบาล' },
        { label: 'บางปะอิน' },
        { label: 'บางปะหัน' },
        { label: 'ผักไห่' },
        { label: 'ภาชี' },
        { label: 'ลาดบัวหลวง' },
        { label: 'วังน้อย' },
        { label: 'เสนา' },
        { label: 'บางซ้าย' },
        { label: 'อุทัย' },
        { label: 'มหาราช' },
        { label: 'บ้านแพรก' },
    ].map(amphoe => arrayConvert(amphoe)),

    อ่างทอง: [
        { label: 'เมืองอ่างทอง' },
        { label: 'ไชโย' },
        { label: 'ป่าโมก' },
        { label: 'โพธิ์ทอง' },
        { label: 'แสวงหา' },
        { label: 'วิเศษชัยชาญ' },
        { label: 'สามโก้' },
    ].map(amphoe => arrayConvert(amphoe)),

    ลพบุรี: [
        { label: 'เมืองลพบุรี' },
        { label: 'พัฒนานิคม' },
        { label: 'โคกสำโรง' },
        { label: 'ชัยบาดาล' },
        { label: 'ท่าวุ้ง' },
        { label: 'บ้านหมี่' },
        { label: 'ท่าหลวง' },
        { label: 'สระโบสถ์' },
        { label: 'โคกเจริญ' },
        { label: 'ลำสนธิ' },
        { label: 'หนองม่วง' },
    ].map(amphoe => arrayConvert(amphoe)),

    สิงห์บุรี: [
        { label: 'เมืองสิงห์บุรี' },
        { label: 'บางระจัน' },
        { label: 'ค่ายบางระจัน' },
        { label: 'พรหมบุรี' },
        { label: 'ท่าช้าง' },
        { label: 'อินทร์บุรี' },
    ].map(amphoe => arrayConvert(amphoe)),

    ชัยนาท: [
        { label: 'เมืองชัยนาท' },
        { label: 'มโนรมย์' },
        { label: 'วัดสิงห์' },
        { label: 'สรรพยา' },
        { label: 'สรรคบุรี' },
        { label: 'หันคา' },
        { label: 'หนองมะโมง' },
        { label: 'เนินขาม' },
    ].map(amphoe => arrayConvert(amphoe)),

    สระบุรี: [
        { label: 'เมืองสระบุรี' },
        { label: 'แก่งคอย' },
        { label: 'หนองแค' },
        { label: 'วิหารแดง' },
        { label: 'หนองแซง' },
        { label: 'บ้านหมอ' },
        { label: 'ดอนพุด' },
        { label: 'หนองโดน' },
        { label: 'พระพุทธบาท' },
        { label: 'เสาไห้' },
        { label: 'มวกเหล็ก' },
        { label: 'วังม่วง' },
        { label: 'เฉลิมพระเกียรติ' },
    ].map(amphoe => arrayConvert(amphoe)),

    ชลบุรี: [
        { label: 'เมืองชลบุรี' },
        { label: 'บ้านบึง' },
        { label: 'หนองใหญ่' },
        { label: 'บางละมุง' },
        { label: 'พานทอง' },
        { label: 'พนัสนิคม' },
        { label: 'ศรีราชา' },
        { label: 'เกาะสีชัง' },
        { label: 'สัตหีบ' },
        { label: 'บ่อทอง' },
        { label: 'เกาะจันทร์' },
        { label: 'บางละมุง' },
    ].map(amphoe => arrayConvert(amphoe)),

    ระยอง: [
        { label: 'เมืองระยอง' },
        { label: 'บ้านฉาง' },
        { label: 'แกลง' },
        { label: 'วังจันทร์' },
        { label: 'บ้านค่าย' },
        { label: 'ปลวกแดง' },
        { label: 'เขาชะเมา' },
        { label: 'นิคมพัฒนา' },
    ].map(amphoe => arrayConvert(amphoe)),

    จันทบุรี: [
        { label: 'เมืองจันทบุรี' },
        { label: 'ขลุง' },
        { label: 'ท่าใหม่' },
        { label: 'โป่งน้ำร้อน' },
        { label: 'มะขาม' },
        { label: 'แหลมสิงห์' },
        { label: 'สอยดาว' },
        { label: 'แก่งหางแมว' },
        { label: 'นายายอาม' },
        { label: 'เขาคิชฌกูฏ' },
    ].map(amphoe => arrayConvert(amphoe)),

    ตราด: [
        { label: 'เมืองตราด' },
        { label: 'คลองใหญ่' },
        { label: 'เขาสมิง' },
        { label: 'บ่อไร่' },
        { label: 'แหลมงอบ' },
        { label: 'เกาะกูด' },
        { label: 'เกาะช้าง' },
    ].map(amphoe => arrayConvert(amphoe)),

    ฉะเชิงเทรา: [
        { label: 'เมืองฉะเชิงเทรา' },
        { label: 'บางคล้า' },
        { label: 'บางน้ำเปรี้ยว' },
        { label: 'บางปะกง' },
        { label: 'บ้านโพธิ์' },
        { label: 'พนมสารคาม' },
        { label: 'ราชสาส์น' },
        { label: 'สนามชัยเขต' },
        { label: 'แปลงยาว' },
        { label: 'ท่าตะเกียบ' },
        { label: 'คลองเขื่อน' },
    ].map(amphoe => arrayConvert(amphoe)),

    ปราจีนบุรี: [
        { label: 'เมืองปราจีนบุรี' },
        { label: 'กบินทร์บุรี' },
        { label: 'นาดี' },
        { label: 'บ้านสร้าง' },
        { label: 'ประจันตคาม' },
        { label: 'ศรีมหาโพธิ' },
        { label: 'ศรีมโหสถ' },
    ].map(amphoe => arrayConvert(amphoe)),

    นครนายก: [
        { label: 'เมืองนครนายก' },
        { label: 'ปากพลี' },
        { label: 'บ้านนา' },
        { label: 'องครักษ์' },
    ].map(amphoe => arrayConvert(amphoe)),

    สระแก้ว: [
        { label: 'เมืองสระแก้ว' },
        { label: 'คลองหาด' },
        { label: 'ตาพระยา' },
        { label: 'วังน้ำเย็น' },
        { label: 'วัฒนานคร' },
        { label: 'อรัญประเทศ' },
        { label: 'เขาฉกรรจ์' },
        { label: 'โคกสูง' },
        { label: 'วังสมบูรณ์' },
    ].map(amphoe => arrayConvert(amphoe)),

    นครราชสีมา: [
        { label: 'เมืองนครราชสีมา' },
        { label: 'ครบุรี' },
        { label: 'เสิงสาง' },
        { label: 'คง' },
        { label: 'บ้านเหลื่อม' },
        { label: 'จักราช' },
        { label: 'โชคชัย' },
        { label: 'ด่านขุนทด' },
        { label: 'โนนไทย' },
        { label: 'โนนสูง' },
        { label: 'ขามสะแกแสง' },
        { label: 'บัวใหญ่' },
        { label: 'ประทาย' },
        { label: 'ปักธงชัย' },
        { label: 'พิมาย' },
        { label: 'ห้วยแถลง' },
        { label: 'ชุมพวง' },
        { label: 'สูงเนิน' },
        { label: 'ขามทะเลสอ' },
        { label: 'สีคิ้ว' },
        { label: 'ปากช่อง' },
        { label: 'หนองบุญมาก' },
        { label: 'แก้งสนามนาง' },
        { label: 'โนนแดง' },
        { label: 'วังน้ำเขียว' },
        { label: 'เทพารัษ์' },
        { label: 'เมืองยาง' },
        { label: 'พระทองคำ' },
        { label: 'ลำทะเมนชัย' },
        { label: 'บัวลาย' },
        { label: 'สีดา' },
        { label: 'เฉลิมพระเกียรติ' },
    ].map(amphoe => arrayConvert(amphoe)),

    บุรีรัมย์: [
        { label: 'เมืองบุรีรัมย์' },
        { label: 'คูเมือง' },
        { label: 'กระสัง' },
        { label: 'นางรอง' },
        { label: 'หนองกี่' },
        { label: 'ละหานทราย' },
        { label: 'ประโคนชัย' },
        { label: 'บ้านกรวด' },
        { label: 'พุทไธสง' },
        { label: 'ลำปลายมาศ' },
        { label: 'สตึก' },
        { label: 'ปะคำ' },
        { label: 'นาโพธิ์' },
        { label: 'หนองหงส์' },
        { label: 'พลับพลาชัย' },
        { label: 'ห้วยราช' },
        { label: 'โนนสุวรรณ' },
        { label: 'ชำนิ' },
        { label: 'บ้านใหม่ไชยพจน์' },
        { label: 'โนนดินแดง' },
        { label: 'บ้านด่าน' },
        { label: 'แคนดง' },
        { label: 'เฉลิมพระเกียรติ' },
    ].map(amphoe => arrayConvert(amphoe)),

    สุรินทร์: [
        { label: 'เมืองสุรินทร์' },
        { label: 'ชุมพลบุรี' },
        { label: 'ท่าตูม' },
        { label: 'จอมพระ' },
        { label: 'ปราสาท' },
        { label: 'กาบเชิง' },
        { label: 'รัตนบุรี' },
        { label: 'สนม' },
        { label: 'ศีขรภูมิ' },
        { label: 'สังขะ' },
        { label: 'ลำดวน' },
        { label: 'สำโรงทาบ' },
        { label: 'บัวเชด' },
        { label: 'พนมดงรัก' },
        { label: 'ศรีณรงค์' },
        { label: 'เขวาสินรินทร์' },
        { label: 'โนนนารายณ์' },
    ].map(amphoe => arrayConvert(amphoe)),

    ศรีสะเกษ: [
        { label: 'เมืองศรีเกษ' },
        { label: 'ยางชุมน้อย' },
        { label: 'กันทรารมย์' },
        { label: 'กันทรลักษ์' },
        { label: 'ขุขันธ์' },
        { label: 'ไพรบึง' },
        { label: 'ปรางค์กู่' },
        { label: 'ขุนหาญ' },
        { label: 'ราษีไศล' },
        { label: 'อุทุมพรพิสัย' },
        { label: 'บึงบูรพ์' },
        { label: 'ห้วยทับทัน' },
        { label: 'โนนคูณ' },
        { label: 'ศรีรัตนะ' },
        { label: 'น้ำเกลี้ยง' },
        { label: 'วังหิน' },
        { label: 'ภูสิงห์' },
        { label: 'เมืองจันทร์' },
        { label: 'เบญจลักษ์' },
        { label: 'พยุห์' },
        { label: 'โพธิ์ศรีสุวรรณ' },
        { label: 'ศิลาลาด' },
    ].map(amphoe => arrayConvert(amphoe)),

    อุบลราชธานี: [
        { label: 'เมืองอุบลราชธานี' },
        { label: 'ศรีเมืองใหม่' },
        { label: 'โขงเจียม' },
        { label: 'เขื่องใน' },
        { label: 'เขมราฐ' },
        { label: 'เดชอุดม' },
        { label: 'นาจะหลวย' },
        { label: 'น้ำยืน' },
        { label: 'บุณฑริก' },
        { label: 'ตระการพืชผล' },
        { label: 'กุดข้าวปุ้น' },
        { label: 'ม่วงสามสิบ' },
        { label: 'วารินชำราบ' },
        { label: 'พิบูลมังสาหาร' },
        { label: 'ตาลสุม' },
        { label: 'โพธิ์ไทร' },
        { label: 'สำโรง' },
        { label: 'ดอนมดแดง' },
        { label: 'สิรินธร' },
        { label: 'ทุ่งศรีอุดม' },
        { label: 'นาเยีย' },
        { label: 'นาตาล' },
        { label: 'เหล่าเสือโก้ก' },
        { label: 'สว่างวีระวงศ์' },
        { label: 'น้ำขุ่น' },
    ].map(amphoe => arrayConvert(amphoe)),

    ยโสธร: [
        { label: 'เมืองยโสธร' },
        { label: 'ทรายมูล' },
        { label: 'กุดชุม' },
        { label: 'คำเขื่อนแก้ว' },
        { label: 'ป่าติ้ว' },
        { label: 'มหาชนะชัย' },
        { label: 'ค้อวัง' },
        { label: 'เลิงนกทา' },
        { label: 'ไทยเจริญ' },
    ].map(amphoe => arrayConvert(amphoe)),

    ชัยภูมิ: [
        { label: 'เมืองหนองบัวลำภู' },
        { label: 'บ้านเขว้า' },
        { label: 'คอนสวรรค์' },
        { label: 'เกษตรสมบูรณ์' },
        { label: 'หนองบัวแดง' },
        { label: 'จัตุรัส' },
        { label: 'บำเหน็จณรงค์' },
        { label: 'หนองบัวระเหว' },
        { label: 'เทพสถิต' },
        { label: 'ภูเขียว' },
        { label: 'บ้านแท่น' },
        { label: 'แก้งคร้อ' },
        { label: 'คอนสาร' },
        { label: 'ภักดีชุมพล' },
        { label: 'เนินสง่า' },
        { label: 'ซับใหญ่' },
    ].map(amphoe => arrayConvert(amphoe)),

    อำนาจเจริญ: [
        { label: 'เมืองอำนาจเจริญ' },
        { label: 'ชานุมาน' },
        { label: 'ปทุมราชวงศา' },
        { label: 'พนา' },
        { label: 'เสนางคนิคม' },
        { label: 'หัวตะพาน' },
        { label: 'ลืออำนาจ' },
    ].map(amphoe => arrayConvert(amphoe)),

    บึงกาฬ: [
        { label: 'บึงกาฬ' },
        { label: 'พรเจริญ' },
        { label: 'โซ่พิสัย' },
        { label: 'เซกา' },
        { label: 'ปากคาด' },
        { label: 'บึงโขงหลง' },
        { label: 'ศรีวิไล' },
        { label: 'บุ่งคล้า' },
    ].map(amphoe => arrayConvert(amphoe)),

    หนองบัวลำภู: [
        { label: 'เมืองหนองบัวลำภู' },
        { label: 'นากลาง' },
        { label: 'โนนสัง' },
        { label: 'ศรีบุญเรือง' },
        { label: 'สุวรรณคูหา' },
        { label: 'นาวัง' },
    ].map(amphoe => arrayConvert(amphoe)),

    ขอนแก่น: [
        { label: 'เมืองขอนแก่น' },
        { label: 'บ้านฝาง' },
        { label: 'พระยืน' },
        { label: 'หนองเรือ' },
        { label: 'ชุมแพ' },
        { label: 'สีชมพู' },
        { label: 'น้ำพอง' },
        { label: 'อุบลรัตน์' },
        { label: 'กระนวน' },
        { label: 'บ้านไผ่' },
        { label: 'เปือยน้อย' },
        { label: 'พล' },
        { label: 'แวงใหญ่' },
        { label: 'แวงน้อย' },
        { label: 'หนองสองห้อง' },
        { label: 'เวียงเก่า' },
        { label: 'มัญจาคีรี' },
        { label: 'ชนบท' },
        { label: 'เขาสวนกวาง' },
        { label: 'ภูผาม่าน' },
        { label: 'ซำสูง' },
        { label: 'โคกโพธิ์' },
        { label: 'หนองนา' },
        { label: 'บ้านแฮ' },
        { label: 'โนนศิลา' },
    ].map(amphoe => arrayConvert(amphoe)),

    อุดรธานี: [
        { label: 'เมืองอุดรธานี' },
        { label: 'กุดจับ' },
        { label: 'หนองวัวซอ' },
        { label: 'กุมภวาปี' },
        { label: 'โนนสะอาด' },
        { label: 'หนองหาน' },
        { label: 'ทุ่งฝน' },
        { label: 'ไชยวาน' },
        { label: 'ศรีธาตุ' },
        { label: 'วังสามหมอ' },
        { label: 'บ้านดุง' },
        { label: 'บ้านผือ' },
        { label: 'น้ำโสม' },
        { label: 'เพ็ญ' },
        { label: 'สร้างคอม' },
        { label: 'หนองแสง' },
        { label: 'นายูง' },
        { label: 'พิบูลย์รักษ์' },
        { label: 'กู่แก้ว' },
        { label: 'ประจักษ์' },
    ].map(amphoe => arrayConvert(amphoe)),

    เลย: [
        { label: 'เมืองเลย' },
        { label: 'นาด้วง' },
        { label: 'เชียงคาน' },
        { label: 'ปากชม' },
        { label: 'ด่านซ้าย' },
        { label: 'นาแห้ว' },
        { label: 'ภูเรือ' },
        { label: 'ท่าลี่' },
        { label: 'วังสะพุง' },
        { label: 'ภูกระดึง' },
        { label: 'ภูหลวง' },
        { label: 'ผาขาว' },
        { label: 'เอราวัณ' },
        { label: 'หนองหิน' },
    ].map(amphoe => arrayConvert(amphoe)),

    หนองคาย: [
        { label: 'เมืองหนองคาย' },
        { label: 'ท่าบ่อ' },
        { label: 'โพนพิสัย' },
        { label: 'ศรีเชียงใหม่' },
        { label: 'สังคม' },
        { label: 'สระใคร' },
        { label: 'เฝ้าไร่' },
        { label: 'รัตนวาปี' },
        { label: 'โพธิ์ตาก' },
    ].map(amphoe => arrayConvert(amphoe)),

    มหาสารคาม: [
        { label: 'เมืองมหาสารคาม' },
        { label: 'แกดำ' },
        { label: 'โกสุมพิสัย' },
        { label: 'กันทรวิชัย' },
        { label: 'เชียงยืน' },
        { label: 'บรบือ' },
        { label: 'นาเชือก' },
        { label: 'พยัคฆภูมิพิสัย' },
        { label: 'วาปีปทุม' },
        { label: 'นาดูน' },
        { label: 'ยางสีสุราช' },
        { label: 'กุดรัง' },
        { label: 'ชื่นชม' },
    ].map(amphoe => arrayConvert(amphoe)),

    ร้อยเอ็ด: [
        { label: 'เมืองร้อยเอ็ด' },
        { label: 'ร้องกวาง' },
        { label: 'ปทุมรัตต์' },
        { label: 'จตุรพักตรพิมาน' },
        { label: 'ธวัชบุรี' },
        { label: 'พนมไพร' },
        { label: 'โพนทอง' },
        { label: 'โพธิ์ชัย' },
        { label: 'หนองพอก' },
        { label: 'เสลภูมิ' },
        { label: 'สุวรรณภูมิ' },
        { label: 'เมืองสรวง' },
        { label: 'โพนทราย' },
        { label: 'อาจสามารถ' },
        { label: 'เมยวดี' },
        { label: 'ศรีสมเด็จ' },
        { label: 'จังหาร' },
        { label: 'เชียงขวัญ' },
        { label: 'หนองฮี' },
        { label: 'ทุ่งเขาหลวง' },
    ].map(amphoe => arrayConvert(amphoe)),

    กาฬสินธุ์: [
        { label: 'เมืองกาฬสินธ์' },
        { label: 'นามน' },
        { label: 'กมลาไสย' },
        { label: 'ร่องคำ' },
        { label: 'กุฉินารายณ์' },
        { label: 'เขาวง' },
        { label: 'ยางตลาด' },
        { label: 'ห้วยเม็ก' },
        { label: 'สหัสขันธ์' },
        { label: 'คำม่วง' },
        { label: 'ท่าคันโท' },
        { label: 'หนองกุงศรี' },
        { label: 'สมเด็จ' },
        { label: 'ห้วยผึ้ง' },
        { label: 'สามชัย' },
        { label: 'นาคู' },
        { label: 'ดอนจาน' },
        { label: 'ฆ้องชัยพัฒนา' },
    ].map(amphoe => arrayConvert(amphoe)),

    สกลนคร: [
        { label: 'เมืองสกลนคร' },
        { label: 'กุสุมาลย์' },
        { label: 'กุดบาก' },
        { label: 'พรรณานิคม' },
        { label: 'พังโคน' },
        { label: 'วาริชภูมิ' },
        { label: 'นิคมน้ำอูน' },
        { label: 'วานรนิวาส' },
        { label: 'คำตากล้า' },
        { label: 'บ้านม่วง' },
        { label: 'อากาศอำนวย' },
        { label: 'สว่างแดนดิน' },
        { label: 'ส่องดาว' },
        { label: 'เต่างอย' },
        { label: 'โคกศรีสุพรรณ' },
        { label: 'เจริญศิลป์' },
        { label: 'โพนนาแก้ว' },
        { label: 'ภูพาน' },
    ].map(amphoe => arrayConvert(amphoe)),

    นครพนม: [
        { label: 'เมืองนครพนม' },
        { label: 'ปลาปาก' },
        { label: 'ท่าอุเทน' },
        { label: 'บ้านแพง' },
        { label: 'ธาตุพนม' },
        { label: 'เรณูนคร' },
        { label: 'นาแก' },
        { label: 'ศรีสงคราม' },
        { label: 'นาหว้า' },
        { label: 'โพนสวรรค์' },
        { label: 'นาทม' },
        { label: 'วังยาง' },
    ].map(amphoe => arrayConvert(amphoe)),

    มุกดาหาร: [
        { label: 'เมืองมุกดาหาร' },
        { label: 'นิคมคำสร้อย' },
        { label: 'ดอนตาล' },
        { label: 'ดงหลวง' },
        { label: 'คำชะอี' },
        { label: 'ว่านใหญ่' },
        { label: 'หนองสูง' },
    ].map(amphoe => arrayConvert(amphoe)),

    เชียงใหม่: [
        { label: 'เมืองเชียงใหม่' },
        { label: 'จอมทอง' },
        { label: 'แม่แจ่ม' },
        { label: 'เชียงดาว' },
        { label: 'ดอยสะเก็ด' },
        { label: 'แม่แตง' },
        { label: 'แม่ริม' },
        { label: 'สะเมิง' },
        { label: 'ฝาง' },
        { label: 'แม่อาย' },
        { label: 'พร้าว' },
        { label: 'สันป่าตอง' },
        { label: 'สันกำแพง' },
        { label: 'สันทราย' },
        { label: 'หางดง' },
        { label: 'ฮอด' },
        { label: 'ดอยเต่า' },
        { label: 'อมก๋อย' },
        { label: 'สารภี' },
        { label: 'เวียงแหง' },
        { label: 'ไชยปราการ' },
        { label: 'แม่วาง' },
        { label: 'แม่ออน' },
        { label: 'ดอยหล่อ' },
    ].map(amphoe => arrayConvert(amphoe)),

    ลำพูน: [
        { label: 'เมืองลำพูน' },
        { label: 'แม่ทา' },
        { label: 'บ้านโฮ่ง' },
        { label: 'ลี้' },
        { label: 'ทุ่งหัวช้าง' },
        { label: 'ป่าซาง' },
        { label: 'บ้านธิ' },
        { label: 'เวียงหนองล่อง' },
    ].map(amphoe => arrayConvert(amphoe)),

    ลำปาง: [
        { label: 'เมืองลำปาง' },
        { label: 'แม่เมาะ' },
        { label: 'เกาะคา' },
        { label: 'เสริมงาม' },
        { label: 'งาว' },
        { label: 'แจ้ห่ม' },
        { label: 'วังเหนือ' },
        { label: 'เถิน' },
        { label: 'แม่พริก' },
        { label: 'แม่ทะ' },
        { label: 'สบปราบ' },
        { label: 'ห้างฉัตร' },
        { label: 'เมืองปาน' },
    ].map(amphoe => arrayConvert(amphoe)),

    อุตรดิตถ์: [
        { label: 'เมืองอุตรดิตถ์' },
        { label: 'ตรอน' },
        { label: 'ท่าปลา' },
        { label: 'น้ำปาด' },
        { label: 'ฟากท่า' },
        { label: 'บ้านโคก' },
        { label: 'พิชัย' },
        { label: 'ลับแล' },
        { label: 'ทองแสนขัน' },
    ].map(amphoe => arrayConvert(amphoe)),

    แพร่: [
        { label: 'เมืองแพร่' },
        { label: 'ร้องกวาง' },
        { label: 'ลอง' },
        { label: 'สูงเม่น' },
        { label: 'เด่นชัย' },
        { label: 'สอง' },
        { label: 'วังชิ้น' },
        { label: 'หนองม่วงไข่' },
    ].map(amphoe => arrayConvert(amphoe)),

    น่าน: [
        { label: 'เมืองน่าน' },
        { label: 'แม่จริม' },
        { label: 'บ้านหลวง' },
        { label: 'นาน้อย' },
        { label: 'ปัว' },
        { label: 'ท่าวังผา' },
        { label: 'เวียงสา' },
        { label: 'ทุ่งช้าง' },
        { label: 'เชียงกลาง' },
        { label: 'นาหมื่น' },
        { label: 'สันติสุข' },
        { label: 'บ่อเกลือ' },
        { label: 'สองแคว' },
        { label: 'ภูเพียง' },
        { label: 'เฉลิมพระเกียรติ' },
    ].map(amphoe => arrayConvert(amphoe)),

    พะเยา: [
        { label: 'เมืองพะเยา' },
        { label: 'จุน' },
        { label: 'เชียงคำ' },
        { label: 'เชียงม่วน' },
        { label: 'ดอกคำใต้' },
        { label: 'ปง' },
        { label: 'แม่ใจ' },
        { label: 'ภูซาง' },
        { label: 'ภูกามยาว' },
    ].map(amphoe => arrayConvert(amphoe)),

    เชียงราย: [
        { label: 'เมืองเชียงราย' },
        { label: 'เวียงชัย' },
        { label: 'เชียงของ' },
        { label: 'เทิง' },
        { label: 'พาน' },
        { label: 'ป่าแดด' },
        { label: 'แม่จัน' },
        { label: 'เชียงแสน' },
        { label: 'แม่สาย' },
        { label: 'แม่สรวย' },
        { label: 'เวียงป่าเป้า' },
        { label: 'พญาเม็งราย' },
        { label: 'เวียงแก่น' },
        { label: 'ขุนตาล' },
        { label: 'แม่ฟ้าหลวง' },
        { label: 'แม่ลาว' },
        { label: 'เวียงเชียงรุ้ง' },
        { label: 'ดอยหลวง' },
    ].map(amphoe => arrayConvert(amphoe)),

    แม่ฮ่องสอน: [
        { label: 'เมืองแม่ฮ่องสอน' },
        { label: 'ขุนยวม' },
        { label: 'ปาย' },
        { label: 'แม่สะเรียง' },
        { label: 'แม่ลาน้อย' },
        { label: 'สบเมย' },
        { label: 'ปางมะผ้า' },
    ].map(amphoe => arrayConvert(amphoe)),

    นครสวรรค์: [
        { label: 'เมืองนครสวรรค์' },
        { label: 'โกรกพระ' },
        { label: 'ชุมแสง' },
        { label: 'หนองบัว' },
        { label: 'บรรพตพิสัย' },
        { label: 'เก้าเลี้ยว' },
        { label: 'ตาคลี' },
        { label: 'ท่าตะโก' },
        { label: 'ไพศาลี' },
        { label: 'พยุหะคีรี' },
        { label: 'ลาดยาว' },
        { label: 'ตากฟ้า' },
        { label: 'แม่วงก์' },
        { label: 'แม่เปิน' },
        { label: 'ชุมตาบง' },
    ].map(amphoe => arrayConvert(amphoe)),

    อุทัยธานี: [
        { label: 'เมืองอุทัยธานี' },
        { label: 'ทัพทัน' },
        { label: 'สว่างอารมณ์' },
        { label: 'หนองฉาง' },
        { label: 'หนองขาหย่าง' },
        { label: 'บ้านไร่' },
        { label: 'ลานสัก' },
        { label: 'ห้วยคต' },
    ].map(amphoe => arrayConvert(amphoe)),

    กำแพงเพชร: [
        { label: 'เมืองกำแพงเพชร' },
        { label: 'ไทรงาม' },
        { label: 'คลองลาน' },
        { label: 'ขาณุวรลักษบุรี' },
        { label: 'คลองขลุง' },
        { label: 'พรานกระต่าย' },
        { label: 'ลานกระบือ' },
        { label: 'ทรายทองวัฒนา' },
        { label: 'ปางศิลาทอง' },
        { label: 'บึงสามัคคี' },
        { label: 'โกสัมพีนคร' },
    ].map(amphoe => arrayConvert(amphoe)),

    ตาก: [
        { label: 'เมืองตาก' },
        { label: 'บ้านตาก' },
        { label: 'สามเงา' },
        { label: 'แม่ระมาด' },
        { label: 'ท่าสองยาง' },
        { label: 'แม่สอด' },
        { label: 'พบพระ' },
        { label: 'อุ้มผาง' },
        { label: 'วังเจ้า' },
    ].map(amphoe => arrayConvert(amphoe)),

    สุโขทัย: [
        { label: 'เมืองสุโขทัย' },
        { label: 'บ้านด่านลานหอย' },
        { label: 'คีรีมาศ' },
        { label: 'กงไกรลาศ' },
        { label: 'ศรีสัชนาลัย' },
        { label: 'ศรีสำโรง' },
        { label: 'สวรรคโลก' },
        { label: 'ศรีนคร' },
        { label: 'ทุ่งเสลี่ยม' },
    ].map(amphoe => arrayConvert(amphoe)),

    พิษณุโลก: [
        { label: 'เมืองพิษณุโลก' },
        { label: 'นครไทย' },
        { label: 'ชาติตระการ' },
        { label: 'บางระกำ' },
        { label: 'บางกระทุ่ม' },
        { label: 'พรหมพิราม' },
        { label: 'วัดโบสถ์' },
        { label: 'วังทอง' },
        { label: 'เนินมะปราง' },
    ].map(amphoe => arrayConvert(amphoe)),

    พิจิตร: [
        { label: 'เมืองพิจิตร' },
        { label: 'วังทรายพูน' },
        { label: 'โพธิ์ประทับช้าง' },
        { label: 'ตะพานหิน' },
        { label: 'บางมูลนาก' },
        { label: 'โพทะเล' },
        { label: 'สามง่าม' },
        { label: 'ทับคล้อ' },
        { label: 'สากเหล็ก' },
        { label: 'บึงนาราง' },
        { label: 'ดงเจริญ' },
        { label: 'วชิรบารมี' },
    ].map(amphoe => arrayConvert(amphoe)),

    เพชรบูรณ์: [
        { label: 'เมืองเพชรบูรณ์' },
        { label: 'ชนแดน' },
        { label: 'หล่มสัก' },
        { label: 'หล่มเก่า' },
        { label: 'วิเชียรบุรี' },
        { label: 'ศรีเทพ' },
        { label: 'หนองไผ่' },
        { label: 'บึงสามพัน' },
        { label: 'น้ำหนาว' },
        { label: 'วังโป่ง' },
        { label: 'เขาค้อ' },
    ].map(amphoe => arrayConvert(amphoe)),

    ราชบุรี: [
        { label: 'เมืองราชบุรี' },
        { label: 'จอมบึง' },
        { label: 'สวนผึ้ง' },
        { label: 'ดำเนินสะดวก' },
        { label: 'บ้านโป่ง' },
        { label: 'บางแพ' },
        { label: 'โพธาราม' },
        { label: 'ปากท่อ' },
        { label: 'วัดเพลง' },
        { label: 'บ้านคา' },
    ].map(amphoe => arrayConvert(amphoe)),

    กาญจนบุรี: [
        { label: 'เมืองกาญจนบุรี' },
        { label: 'ไทรโยค' },
        { label: 'บ่อพลอย' },
        { label: 'ศรีสวัสดิ์' },
        { label: 'ท่ามะกา' },
        { label: 'ท่าม่วง' },
        { label: 'ทองผาภูมิ' },
        { label: 'สังขละบุรี' },
        { label: 'พนมทวน' },
        { label: 'เลาขวัญ' },
        { label: 'ด่านมะขามเตี้ย' },
        { label: 'หนองปรือ' },
        { label: 'ห้วยกระเจา' },
    ].map(amphoe => arrayConvert(amphoe)),

    สุพรรณบุรี: [
        { label: 'เมืองสุพรรณบุรี' },
        { label: 'เดิมบางนางบวช' },
        { label: 'ด่านช้าง' },
        { label: 'บางปลาม้า' },
        { label: 'ศรีประจันต์' },
        { label: 'ดอนเจดีย์' },
        { label: 'สองพี่น้อง' },
        { label: 'สามชุก' },
        { label: 'อู่ทอง' },
        { label: 'หนองหญ้าไซ' },
    ].map(amphoe => arrayConvert(amphoe)),

    นครปฐม: [
        { label: 'เมืองนครปฐม' },
        { label: 'กำแพงแสน' },
        { label: 'นครชัยศรี' },
        { label: 'ดอนตูม' },
        { label: 'บางเลน' },
        { label: 'สามพราน' },
        { label: 'พุทธมณฑล' },
    ].map(amphoe => arrayConvert(amphoe)),

    สมุทรสาคร: [
        { label: 'เมืองสมุทรสาคร' },
        { label: 'กระทุ่มแบน' },
        { label: 'บ้านแพ้ว' },
    ].map(amphoe => arrayConvert(amphoe)),

    สมุทรสงคราม: [
        { label: 'เมืองสมุทรสงคราม' },
        { label: 'บางคนที' },
        { label: 'อัมพวา' },
    ].map(amphoe => arrayConvert(amphoe)),

    เพชรบุรี: [
        { label: 'เมืองเพชรบุรี' },
        { label: 'เขาย้อย' },
        { label: 'หนองหญ้าปล้อง' },
        { label: 'ชะอำ' },
        { label: 'ท่ายาง' },
        { label: 'บ้านลาด' },
        { label: 'บ้านแหลม' },
        { label: 'แก่งกระจาน' },
    ].map(amphoe => arrayConvert(amphoe)),

    ประจวบคีรีขันธ์: [
        { label: 'เมืองประจวบคีรีขันธ์' },
        { label: 'กุยบุรี' },
        { label: 'ทับสะแก' },
        { label: 'บางสะพาน' },
        { label: 'บางสะพานน้อย' },
        { label: 'ปราณบุรี' },
        { label: 'หัวหิน' },
        { label: 'สามร้อยยอด' },
    ].map(amphoe => arrayConvert(amphoe)),

    นครศรีธรรมราช: [
        { label: 'เมืองนครศรีธรรมราช' },
        { label: 'พรหมคีรี' },
        { label: 'ลานสกา' },
        { label: 'ฉวาง' },
        { label: 'พิปูน' },
        { label: 'เชียรใหญ่' },
        { label: 'ชะอวด' },
        { label: 'ท่าศาลา' },
        { label: 'ทุ่งสง' },
        { label: 'นาบอน' },
        { label: 'ทุ่งใหญ่' },
        { label: 'ปากพนัง' },
        { label: 'ร่อนพิบูลย์' },
        { label: 'สิชล' },
        { label: 'ขนอม' },
        { label: 'หัวไทร' },
        { label: 'บางขัน' },
        { label: 'ถ้ำพรรณรา' },
        { label: 'จุฬาภรณ์' },
        { label: 'พระพรหม' },
        { label: 'นบพิตำ' },
        { label: 'ช้างกลาง' },
        { label: 'เฉลิมพระเกียรติ' },
    ].map(amphoe => arrayConvert(amphoe)),

    กระบี่: [
        { label: 'เมืองกระบี่' },
        { label: 'เขาพนม' },
        { label: 'เกาะลันตา' },
        { label: 'คลองท่อม' },
        { label: 'อ่าวลึก' },
        { label: 'ปลายพระยา' },
        { label: 'ลำทับ' },
        { label: 'เหนือคลอง' },
    ].map(amphoe => arrayConvert(amphoe)),

    พังงา: [
        { label: 'เมืองพังงา' },
        { label: 'เกาะยาว' },
        { label: 'กะปง' },
        { label: 'ตะกั่วทุ่ง' },
        { label: 'ตะกั่วป่า' },
        { label: 'คุระบุรี' },
        { label: 'ทับปุด' },
        { label: 'ท้ายเหมือง' },
    ].map(amphoe => arrayConvert(amphoe)),

    ภูเก็ต: [
        { label: 'เมืองภูเก็ต' },
        { label: 'กะทู้' },
        { label: 'ถลาง' },
    ].map(amphoe => arrayConvert(amphoe)),

    สุราษฎร์ธานี: [
        { label: 'เมืองสุราษฎร์ธานี' },
        { label: 'กาญจนดิษฐ์' },
        { label: 'ดอนสัก' },
        { label: 'เกาะสมุย' },
        { label: 'เกาะพะงัน' },
        { label: 'ไชยา' },
        { label: 'ท่าชนะ' },
        { label: 'คีรีรัฐนิคม' },
        { label: 'บ้านขุนตาล' },
        { label: 'พนม' },
        { label: 'ท่าฉาง' },
        { label: 'บ้านนาสาร' },
        { label: 'บ้านนาเดิม' },
        { label: 'เคียนซา' },
        { label: 'เวียงสระ' },
        { label: 'พระแสง' },
        { label: 'พุนพิน' },
        { label: 'ชัยบุรี' },
        { label: 'วิภาวดี' },
    ].map(amphoe => arrayConvert(amphoe)),

    ระนอง: [
        { label: 'เมืองระนอง' },
        { label: 'ละอุ่น' },
        { label: 'กะเปอร์' },
        { label: 'กระบุรี' },
        { label: 'สุขสำราญ' },
    ].map(amphoe => arrayConvert(amphoe)),

    ชุมพร: [
        { label: 'เมืองชุมพร' },
        { label: 'ท่าแซะ' },
        { label: 'ปะทิว' },
        { label: 'หลังสวน' },
        { label: 'ละแม' },
        { label: 'พะโต๊ะ' },
        { label: 'สวี' },
        { label: 'ทุ่งตะโก' },
    ].map(amphoe => arrayConvert(amphoe)),

    สงขลา: [
        { label: 'เมืองสงขลา' },
        { label: 'สทิงพระ' },
        { label: 'จะนะ' },
        { label: 'นาทวี' },
        { label: 'เทพา' },
        { label: 'สะบ้าย้อย' },
        { label: 'ระโนด' },
        { label: 'กระแสสินธุ์' },
        { label: 'รัตภูมิ' },
        { label: 'สะเดา' },
        { label: 'หาดใหญ่' },
        { label: 'นาหม่อม' },
        { label: 'ควนเนียง' },
        { label: 'บางกล่ำ' },
        { label: 'สิงหนคร' },
        { label: 'คลองหอยโข่ง' },
    ].map(amphoe => arrayConvert(amphoe)),

    สตูล: [
        { label: 'เมืองสตูล' },
        { label: 'ควนโดน' },
        { label: 'ควนกาหลง' },
        { label: 'ท่าแพ' },
        { label: 'ละงู' },
        { label: 'ทุ่งหว้า' },
        { label: 'มะนัง' },
    ].map(amphoe => arrayConvert(amphoe)),

    ตรัง: [
        { label: 'เมืองตรัง' },
        { label: 'กันตัง' },
        { label: 'ย่านตาขาว' },
        { label: 'ปะเหลียน' },
        { label: 'สิเกา' },
        { label: 'ห้วยยอด' },
        { label: 'วังวิเศษ' },
        { label: 'นาโยง' },
        { label: 'รัษฎา' },
        { label: 'หาดสำราญ' },
    ].map(amphoe => arrayConvert(amphoe)),

    พัทลุง: [
        { label: 'เมืองพัทลุง' },
        { label: 'กงหรา' },
        { label: 'เขาชัยสน' },
        { label: 'ตะโหมด' },
        { label: 'ควนขนุน' },
        { label: 'ปากพะยูน' },
        { label: 'ศรีบรรพต' },
        { label: 'ป่าบอน' },
        { label: 'บางแก้ว' },
        { label: 'ป่าพยอม' },
        { label: 'ศรีนครินทร์' },
    ].map(amphoe => arrayConvert(amphoe)),

    ปัตตานี: [
        { label: 'เมืองปัตตานี' },
        { label: 'โคกโพธิ์' },
        { label: 'หนองจิก' },
        { label: 'ปะนาเระ' },
        { label: 'มายอ' },
        { label: 'ทุ่งยางแดง' },
        { label: 'สายบุรี' },
        { label: 'ไม้แก่น' },
        { label: 'ยะหริ่ง' },
        { label: 'ยะรัง' },
        { label: 'กะพ้อ' },
        { label: 'แม่ลาน' },
    ].map(amphoe => arrayConvert(amphoe)),

    ยะลา: [
        { label: 'เมืองยะลา' },
        { label: 'เบตง' },
        { label: 'บันนังสตา' },
        { label: 'ธารโต' },
        { label: 'ยะหา' },
        { label: 'รามัน' },
        { label: 'กาบัง' },
        { label: 'กรงปีนัง' },
    ].map(amphoe => arrayConvert(amphoe)),

    นราธิวาส: [
        { label: 'เมืองนราธิวาส' },
        { label: 'ตากใบ' },
        { label: 'บาเจาะ' },
        { label: 'ยี่งอ' },
        { label: 'ระแงะ' },
        { label: 'รือเสาะ' },
        { label: 'ศรีสาคร' },
        { label: 'แว้ง' },
        { label: 'สุคิริน' },
        { label: 'สุไหงโก-ลก' },
        { label: 'สุไหงปาดี' },
        { label: 'จะแนะ' },
        { label: 'เจาะไอร้อง' },
    ].map(amphoe => arrayConvert(amphoe)),

}
export const tambons = {

    /*-----------------------------------กรุงเทพมหานคร-----------------------------------*/

    พระนคร: [
        { label: 'พระบรมมหาราชวัง' },
        { label: 'วังบูรพาภิรมย์' },
        { label: 'วัดราชบพิธ' },
        { label: 'สำราญราษฎร์' },
        { label: 'ศาลเจ้าพ่อเสือ' },
        { label: 'เสาชิงช้า' },
        { label: 'บวรนิเวศ' },
        { label: 'ตลาดยอด' },
        { label: 'ชนะสงคราม' },
        { label: 'บ้านพานถม' },
        { label: 'บางขุนพรหม' },
        { label: 'วัดสามพระยา' },
    ].map(tambons => arrayConvert(tambons)),

    ดุสิต: [
        { label: 'ดุสิต' },
        { label: 'วชิรพยาบาล' },
        { label: 'สวนจิตรลดา' },
        { label: 'สี่แยกมหานาค' },
        { label: 'ถนนนครไชยศรี' },
    ].map(tambons => arrayConvert(tambons)),

    หนองจอก: [
        { label: 'กระทุ่มราย' },
        { label: 'หนองจอก' },
        { label: 'คลองสิบ' },
        { label: 'คลองสิบสอง' },
        { label: 'โคกแฝด' },
        { label: 'คู้ฝั่งเหนือ' },
        { label: 'ลำผักชี' },
        { label: 'ลำต้อยติ่ง' },
    ].map(tambons => arrayConvert(tambons)),

    บางรัก: [
        { label: 'มหาพฤฒาราม' },
        { label: 'สีลม' },
        { label: 'สุริยวงศ์' },
        { label: 'บางรัก' },
        { label: 'สี่พระยา' },
    ].map(tambons => arrayConvert(tambons)),

    บางเขน: [
        { label: 'อนุสาวรีย์' },
        { label: 'ท่าแร้ง' },
    ].map(tambons => arrayConvert(tambons)),

    บางกะปิ: [
        { label: 'คลองจั่น' },
        { label: 'หัวหมาก' },
    ].map(tambons => arrayConvert(tambons)),

    ปทุมวัน: [
        { label: 'รองเมือง' },
        { label: 'วังใหม่' },
        { label: 'ปทุมวัน' },
        { label: 'ลุมพินี' },
    ].map(tambons => arrayConvert(tambons)),

    ป้อมปราบศัตรูพ่าย: [
        { label: 'ป้อมปราบ' },
        { label: 'วัดเทพศิรินทร์' },
        { label: 'คลองมหานาค' },
        { label: 'บ้านบาตร' },
        { label: 'วัดโสมนัส' },
    ].map(tambons => arrayConvert(tambons)),

    พระโขนง: [
        { label: 'บางจาก' }
    ].map(tambons => arrayConvert(tambons)),

    มีนบุรี: [
        { label: 'มีนบุรี' },
        { label: 'แสนแสบ' },
    ].map(tambons => arrayConvert(tambons)),

    ลาดกระบัง: [
        { label: 'ลาดกระบัง' },
        { label: 'คลองสองต้นนุ่น' },
        { label: 'คลองสามประเวศ' },
        { label: 'ลำปลาทิว' },
        { label: 'ทับยาว' },
        { label: 'ขุมทอง' },
    ].map(tambons => arrayConvert(tambons)),

    ยานนาวา: [
        { label: 'ช่องนนทรี' },
        { label: 'บางโพงพาง' },
    ].map(tambons => arrayConvert(tambons)),

    สัมพันธวงศ์: [
        { label: 'จักรวรรดิ' },
        { label: 'สัมพันธวงศ์' },
        { label: 'ตลาดน้อย' },
    ].map(tambons => arrayConvert(tambons)),

    พญาไท: [
        { label: 'สามเสนใน' }
    ].map(tambons => arrayConvert(tambons)),

    ธนบุรี: [
        { label: 'วัดกัลยาณ์' },
        { label: 'หิรัญรูจี' },
        { label: 'บางยี่เรือ' },
        { label: 'บุคคโล' },
        { label: 'ตลาดพลู' },
        { label: 'ดาวคะนอง' },
        { label: 'สำเหร่' },
    ].map(tambons => arrayConvert(tambons)),

    บางกอกใหญ่: [
        { label: 'วัดอรุณ' },
        { label: 'วัดท่าพระ' },
    ].map(tambons => arrayConvert(tambons)),

    ห้วยขวาง: [
        { label: 'ห้วยขวาง' },
        { label: 'บางกะปิ' },
        { label: 'สามเสนนอก' },
    ].map(tambons => arrayConvert(tambons)),

    คลองสาน: [
        { label: 'สมเด็จเจ้าพระยา' },
        { label: 'คลองสาน' },
        { label: 'บางลำภูล่าง' },
        { label: 'คลองต้นไทร' },
    ].map(tambons => arrayConvert(tambons)),

    ตลิ่งชัน: [
        { label: 'คลองชักพระ' },
        { label: 'ตลิ่งชัน' },
        { label: 'ฉิมพลี' },
        { label: 'บางพรม' },
        { label: 'บางระมาด' },
        { label: 'บางเชือกหนัง' },
    ].map(tambons => arrayConvert(tambons)),

    บางกอกน้อย: [
        { label: 'ศิริราช' },
        { label: 'บ้านช่างหล่อ' },
        { label: 'บางขุนนนท์' },
        { label: 'บางขุนศรี' },
        { label: 'อรุณอมรินทร์' },
    ].map(tambons => arrayConvert(tambons)),

    บางขุนเทียน: [
        { label: 'ท่าข้าม' },
        { label: 'แสมดำ' },
    ].map(tambons => arrayConvert(tambons)),

    ภาษีเจริญ: [
        { label: 'บางหว้า' },
        { label: 'บางด้วน' },
        { label: 'บางจาก' },
        { label: 'บางแวก' },
        { label: 'คลองขวาง' },
        { label: 'ปากคลองภาษีเจริญ' },
        { label: 'คูหาสวรรค์' },
    ].map(tambons => arrayConvert(tambons)),

    หนองแขม: [
        { label: 'หนองแขม' },
        { label: 'หนองค้างพลู' },
    ].map(tambons => arrayConvert(tambons)),

    ราษฎร์บูรณะ: [
        { label: 'ราษฎร์บูรณะ' },
        { label: 'บางปะกอก' },
    ].map(tambons => arrayConvert(tambons)),

    บางพลัด: [
        { label: 'บางพลัด' },
        { label: 'บางอ้อ' },
        { label: 'บางบำหรุ' },
        { label: 'บางยี่ขัน' },
    ].map(tambons => arrayConvert(tambons)),

    ดินแดง: [
        { label: 'ดินแดง' }
    ].map(tambons => arrayConvert(tambons)),

    บึงกุ่ม: [
        { label: 'คลองกุ่ม' }
    ].map(tambons => arrayConvert(tambons)),

    สาทร: [
        { label: 'ทุ่งวัดดอน' },
        { label: 'ยานนาวา' },
        { label: 'ทุ่งมหาเมฆ' },
    ].map(tambons => arrayConvert(tambons)),

    บางซื่อ: [
        { label: 'บางซื่อ' }
    ].map(tambons => arrayConvert(tambons)),

    จตุจักร: [
        { label: 'ลาดยาว' },
        { label: 'เสนานิคม' },
        { label: 'จันทรเกษม' },
        { label: 'จอมพล' },
        { label: 'จตุจักร' },
    ].map(tambons => arrayConvert(tambons)),

    บางคอแหลม: [
        { label: 'บางคอแหลม' },
        { label: 'วัดพระยาไกร' },
        { label: 'บางโคล่' },
    ].map(tambons => arrayConvert(tambons)),

    ประเวศ: [
        { label: 'ประเวศ' },
        { label: 'หนองบอน' },
        { label: 'ดอกไม้' },
    ].map(tambons => arrayConvert(tambons)),

    คลองเตย: [
        { label: 'คลองเตย' },
        { label: 'คลองตัน' },
        { label: 'พระโขนง' },
    ].map(tambons => arrayConvert(tambons)),

    สวนหลวง: [
        { label: 'สวนหลวง' }
    ].map(tambons => arrayConvert(tambons)),

    จอมทอง: [
        { label: 'บางขุนเทียน' },
        { label: 'บางค้อ' },
        { label: 'บางมด' },
        { label: 'จอมทอง' },
    ].map(tambons => arrayConvert(tambons)),

    ดอนเมือง: [
        { label: 'สีกัน' }
    ].map(tambons => arrayConvert(tambons)),

    ราชเทวี: [
        { label: 'ทุ่งพญาไท' },
        { label: 'ถนนพญาไท' },
        { label: 'ถนนเพชรบุรี' },
        { label: 'มักกะสัน' },
    ].map(tambons => arrayConvert(tambons)),

    ลาดพร้าว: [
        { label: 'ลาดพร้าว' },
        { label: 'จรเข้บัว' },
    ].map(tambons => arrayConvert(tambons)),

    วัฒนา: [
        { label: 'คลองเตยเหนือ' },
        { label: 'คลองตันเหนือ' },
        { label: 'พระโขนงเหนือ' },
    ].map(tambons => arrayConvert(tambons)),

    บางแค: [
        { label: 'บางแค' },
        { label: 'บางแคเหนือ' },
        { label: 'บางไผ่' },
        { label: 'หลักสอง' },
    ].map(tambons => arrayConvert(tambons)),

    หลักสี่: [
        { label: 'ทุ่งสองห้อง' },
        { label: 'ตลาดบางเขน' },
    ].map(tambons => arrayConvert(tambons)),

    สายไหม: [
        { label: 'สายไหม' },
        { label: 'ออเงิน' },
        { label: 'คลองถนน' },
    ].map(tambons => arrayConvert(tambons)),

    คันนายาว: [
        { label: 'คันนายาว' }
    ].map(tambons => arrayConvert(tambons)),

    สะพานสูง: [
        { label: 'สะพานสูง' }
    ].map(tambons => arrayConvert(tambons)),

    วังทองหลาง: [
        { label: 'วังทองหลาง' }
    ].map(tambons => arrayConvert(tambons)),

    คลองสามวา: [
        { label: 'สามวาตะวันตก' },
        { label: 'สามวาตะวันออก' },
        { label: 'บางชัน' },
        { label: 'ทรายกองดิน' },
        { label: 'ทรายกองดินใต้' },
    ].map(tambons => arrayConvert(tambons)),

    บางนา: [
        { label: 'บางนา' }
    ].map(tambons => arrayConvert(tambons)),

    ทวีวัฒนา: [
        { label: 'ทวีวัฒนา' },
        { label: 'ศาลาธรรมสพน์' },
    ].map(tambons => arrayConvert(tambons)),

    ทุ่งครุ: [
        { label: 'บางมด' },
        { label: 'ทุ่งครุ' },
    ].map(tambons => arrayConvert(tambons)),

    บางบอน: [
        { label: 'บางบอน' }
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------สมุทรปราการ-----------------------------------*/

    เมืองสมุทรปราการ: [
        { label: 'ปากน้ำ' },
        { label: 'สำโรงเหนือ' },
        { label: 'บางเมือง' },
        { label: 'ท้ายบ้าน' },
        { label: 'บางปูใหม่' },
        { label: 'แพรกษา' },
        { label: 'บางโปรง' },
        { label: 'บางปู' },
        { label: 'บางด้วน' },
        { label: 'บางเมืองใหม่' },
        { label: 'เทพารักษ์' },
        { label: 'ท้ายบ้านใหม่' },
        { label: 'แพรกษาใหม่' },
    ].map(tambons => arrayConvert(tambons)),

    บางบ่อ: [
        { label: 'บางบ่อ' },
        { label: 'บ้านระกาศ' },
        { label: 'บางพลีน้อย' },
        { label: 'บางเพรียง' },
        { label: 'คลองด่าน' },
        { label: 'คลองสวน' },
        { label: 'เปร็ง' },
        { label: 'คลองนิยมยาตรา' },
    ].map(tambons => arrayConvert(tambons)),

    บางพลี: [
        { label: 'บางพลีใหญ่' },
        { label: 'บางแก้ว' },
        { label: 'บางปลา' },
        { label: 'บางโฉลง' },
        { label: 'ราชาเทวะ' },
        { label: 'หนองปรือ' },
    ].map(tambons => arrayConvert(tambons)),

    พระประแดง: [
        { label: 'ตลาด' },
        { label: 'บางพึ่ง' },
        { label: 'บางจาก' },
        { label: 'บางครุ' },
        { label: 'บางหญ้าแพรก' },
        { label: 'บางหัวเสือ' },
        { label: 'สำโรงใต้' },
        { label: 'บางยอ' },
        { label: 'บางกะเจ้า' },
        { label: 'บางน้ำผึ้ง' },
        { label: 'บางกระสอบ' },
        { label: 'บางกอบัว' },
        { label: 'ทรงคนอง' },
        { label: 'สำโรง' },
        { label: 'สำโรงกลาง' },
    ].map(tambons => arrayConvert(tambons)),

    พระสมุทรเจดีย์: [
        { label: 'นาเกลือ' },
        { label: 'บ้านคลองสวน' },
        { label: 'แหลมฟ้าผ่า' },
        { label: 'ปากคลองบางปลากด' },
        { label: 'ในคลองบางปลากด' },
    ].map(tambons => arrayConvert(tambons)),

    บางเสาธง: [
        { label: 'บางเสาธง' },
        { label: 'ศีรษะจรเข้น้อย' },
        { label: 'ศีรษะจรเข้ใหญ่' },
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------นนทบุรี-----------------------------------*/

    เมืองนนทบุรี: [
        { label: 'สวนใหญ่' },
        { label: 'ตลาดขวัญ' },
        { label: 'บางเขน' },
        { label: 'บางกระสอ' },
        { label: 'ท่าทราย' },
        { label: 'บางไผ่' },
        { label: 'บางศรีเมือง' },
        { label: 'บางกร่าง' },
        { label: 'ไทรม้า' },
        { label: 'บางรักน้อย' },
    ].map(tambons => arrayConvert(tambons)),

    บางกรวย: [
        { label: 'วัดชลอ' },
        { label: 'บางกรวย' },
        { label: 'บางสีทอง' },
        { label: 'บางขนุน' },
        { label: 'บางขุนกอง' },
        { label: 'บางคูเวียง' },
        { label: 'มหาสวัสดิ์' },
        { label: 'ปลายบาง' },
        { label: 'ศาลากลาง' },
    ].map(tambons => arrayConvert(tambons)),

    บางใหญ่: [
        { label: 'บางม่วง' },
        { label: 'บางแม่นาง' },
        { label: 'บางเลน' },
        { label: 'เสาธงหิน' },
        { label: 'บางใหญ่' },
        { label: 'บ้านใหม่' },
    ].map(tambons => arrayConvert(tambons)),

    บางบัวทอง: [
        { label: 'โสนลอย' },
        { label: 'บางบัวทอง' },
        { label: 'บางรักใหญ่' },
        { label: 'บางคูรัด' },
        { label: 'ละหาร' },
        { label: 'ลำโพ' },
        { label: 'พิมลราช' },
        { label: 'บางรักพัฒนา' },
    ].map(tambons => arrayConvert(tambons)),

    ไทรน้อย: [
        { label: 'ไทรน้อย' },
        { label: 'ราษฎร์นิยม' },
        { label: 'หนองเพรางาย' },
        { label: 'ไทรใหญ่' },
        { label: 'ขุนศรี' },
        { label: 'คลองขวาง' },
        { label: 'ทวีวัฒนา' },
    ].map(tambons => arrayConvert(tambons)),

    ปากเกร็ด: [
        { label: 'ปากเกร็ด' },
        { label: 'บางตลาด' },
        { label: 'บ้านใหม่' },
        { label: 'บางพูด' },
        { label: 'บางตะไนย์' },
        { label: 'คลองพระอุดม' },
        { label: 'ท่าอิฐ' },
        { label: 'เกาะเกร็ด' },
        { label: 'อ้อมเกร็ด' },
        { label: 'คลองข่อย' },
        { label: 'บางพลับ' },
        { label: 'คลองเกลือ' },
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------ปทุมธานี-----------------------------------*/

    เมืองปทุมธานี: [
        { label: 'บางปรอก' },
        { label: 'บ้านใหม่' },
        { label: 'บ้านกลาง' },
        { label: 'บ้านฉาง' },
        { label: 'บ้านกระแชง' },
        { label: 'บางขะแยง' },
        { label: 'บางคูวัด' },
        { label: 'บางหลวง' },
        { label: 'บางเดื่อ' },
        { label: 'บางพูด' },
        { label: 'บางพูน' },
        { label: 'บางกะดี' },
        { label: 'สวนพริกไทย' },
        { label: 'หลักหก' },
    ].map(tambons => arrayConvert(tambons)),

    คลองหลวง: [
        { label: 'คลองหนึ่ง' },
        { label: 'คลองสอง' },
        { label: 'คลองสาม' },
        { label: 'คลองสี่' },
        { label: 'คลองห้า' },
        { label: 'คลองหก' },
        { label: 'คลองเจ็ด' },
    ].map(tambons => arrayConvert(tambons)),

    ธัญบุรี: [
        { label: 'ประชาธิปัตย์' },
        { label: 'บึงยี่โถ' },
        { label: 'รังสิต' },
        { label: 'ลำผักกูด' },
        { label: 'บึงสนั่น' },
        { label: 'บึงน้ำรักษ์' },
    ].map(tambons => arrayConvert(tambons)),

    หนองเสือ: [
        { label: 'บึงบา' },
        { label: 'บึงบอน' },
        { label: 'บึงกาสาม' },
        { label: 'บึงชำอ้อ' },
        { label: 'หนองสามวัง' },
        { label: 'ศาลาครุ' },
        { label: 'นพรัตน์' },
    ].map(tambons => arrayConvert(tambons)),

    ลาดหลุมแก้ว: [
        { label: 'ระแหง' },
        { label: 'ลาดหลุมแก้ว' },
        { label: 'คูบางหลวง' },
        { label: 'คูขวาง' },
        { label: 'คลองพระอุดม' },
        { label: 'บ่อเงิน' },
        { label: 'หน้าไม้' },
    ].map(tambons => arrayConvert(tambons)),

    ลำลูกกา: [
        { label: 'คูคต' },
        { label: 'ลาดสวาย' },
        { label: 'บึงคำพร้อย' },
        { label: 'ลำลูกกา' },
        { label: 'บึงทองหลาง' },
        { label: 'ลำไทร' },
        { label: 'บึงคอไห' },
        { label: 'พืชอุดม' },
    ].map(tambons => arrayConvert(tambons)),

    สามโคก: [
        { label: 'บางเตย' },
        { label: 'คลองควาย' },
        { label: 'สามโคก' },
        { label: 'กระแชง' },
        { label: 'บางโพธิ์เหนือ' },
        { label: 'เชียงรากใหญ่' },
        { label: 'บ้านปทุม' },
        { label: 'บ้านงิ้ว' },
        { label: 'เชียงรากน้อย' },
        { label: 'บางกระบือ' },
        { label: 'ท้ายเกาะ' },
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------พระนครศรีอยุธยา-----------------------------------*/

    พระนครศรีอยุธยา: [
        { label: 'ประตูชัย' },
        { label: 'กะมัง' },
        { label: 'หอรัตนไชย' },
        { label: 'หัวรอ' },
        { label: 'ท่าวาสุกรี' },
        { label: 'ไผ่ลิง' },
        { label: 'ปากกราน' },
        { label: 'ภูเขาทอง' },
        { label: 'สำเภาล่ม' },
        { label: 'สวนพริก' },
        { label: 'คลองตะเคียน' },
        { label: 'วัดตูม' },
        { label: 'หันตรา' },
        { label: 'ลุมพลี' },
        { label: 'บ้านใหม่' },
        { label: 'บ้านเกาะ' },
        { label: 'คลองสวนพลู' },
        { label: 'คลองสระบัว' },
        { label: 'เกาะเรียน' },
        { label: 'บ้านป้อม' },
        { label: 'บ้านรุน' },
    ].map(tambons => arrayConvert(tambons)),

    ท่าเรือ: [
        { label: 'ท่าเรือ' },
        { label: 'จำปา' },
        { label: 'ท่าหลวง' },
        { label: 'บ้านร่อม' },
        { label: 'ศาลาลอย' },
        { label: 'วังแดง' },
        { label: 'โพธิ์เอน' },
        { label: 'ปากท่า' },
        { label: 'หนองขนาก' },
        { label: 'ท่าเจ้าสนุก' },
    ].map(tambons => arrayConvert(tambons)),

    นครหลวง: [
        { label: 'นครหลวง' },
        { label: 'ท่าช้าง' },
        { label: 'บ่อโพง' },
        { label: 'บ้านชุ้ง' },
        { label: 'ปากจั่น' },
        { label: 'บางระกำ' },
        { label: 'บางพระครู' },
        { label: 'แม่ลา' },
        { label: 'หนองปลิง' },
        { label: 'คลองสะแก' },
        { label: 'สามไถ' },
        { label: 'พระนอน' },
    ].map(tambons => arrayConvert(tambons)),

    บางไทร: [
        { label: 'บางไทร' },
        { label: 'บางพลี' },
        { label: 'สนามชัย' },
        { label: 'บ้านแป้ง' },
        { label: 'หน้าไม้' },
        { label: 'บางยี่โท' },
        { label: 'แคออก' },
        { label: 'แคตก' },
        { label: 'ช่างเหล็ก' },
        { label: 'กระแชง' },
        { label: 'บ้านกลึง' },
        { label: 'ช้างน้อย' },
        { label: 'ห่อหมก' },
        { label: 'ไผ่พระ' },
        { label: 'กกแก้วบูรพา' },
        { label: 'ไม้ตรา' },
        { label: 'บ้านม้า' },
        { label: 'บ้านเกาะ' },
        { label: 'ราชคราม' },
        { label: 'ช้างใหญ่' },
        { label: 'โพแตง' },
        { label: 'เชียงรากน้อย' },
        { label: 'โคกช้าง' },
    ].map(tambons => arrayConvert(tambons)),

    บางบาล: [
        { label: 'บางบาล' },
        { label: 'วัดยม' },
        { label: 'ไทรน้อย' },
        { label: 'สะพานไทย' },
        { label: 'มหาพราหมณ์' },
        { label: 'กบเจา' },
        { label: 'บ้านคลัง' },
        { label: 'พระขาว' },
        { label: 'น้ำเต้า' },
        { label: 'ทางช้าง' },
        { label: 'วัดตะกู' },
        { label: 'บางหลวง' },
        { label: 'บางหลวงโดด' },
        { label: 'บางหัก' },
        { label: 'บางชะนี' },
        { label: 'บ้านกุ่ม' },
    ].map(tambons => arrayConvert(tambons)),

    บางปะอิน: [
        { label: 'บ้านเลน' },
        { label: 'เชียงรากน้อย' },
        { label: 'บ้านโพ' },
        { label: 'บ้านกรด' },
        { label: 'บางกระสั้น' },
        { label: 'คลองจิก' },
        { label: 'บ้านหว้า' },
        { label: 'วัดยม' },
        { label: 'บางประแดง' },
        { label: 'สามเรือน' },
        { label: 'เกาะเกิด' },
        { label: 'บ้านพลับ' },
        { label: 'บ้านแป้ง' },
        { label: 'คุ้งลาน' },
        { label: 'ตลิ่งชัน' },
        { label: 'บ้านสร้าง' },
        { label: 'ตลาดเกรียบ' },
        { label: 'ขนอนหลวง' },
    ].map(tambons => arrayConvert(tambons)),

    บางปะหัน: [
        { label: 'บางปะหัน' },
        { label: 'ขยาย' },
        { label: 'บางเดื่อ' },
        { label: 'เสาธง' },
        { label: 'ทางกลาง' },
        { label: 'บางเพลิง' },
        { label: 'หันสัง' },
        { label: 'บางนางร้า' },
        { label: 'ตานิม' },
        { label: 'ทับน้ำ' },
        { label: 'บ้านม้า' },
        { label: 'ขวัญเมือง' },
        { label: 'บ้านลี่' },
        { label: 'โพธิ์สามต้น' },
        { label: 'พุทเลา' },
        { label: 'ตาลเอน' },
        { label: 'บ้านขล้อ' },
    ].map(tambons => arrayConvert(tambons)),

    ผักไห่: [
        { label: 'ผักไห่' },
        { label: 'อมฤต' },
        { label: 'บ้านแค' },
        { label: 'ลาดน้ำเค็ม' },
        { label: 'ตาลาน' },
        { label: 'ท่าดินแดง' },
        { label: 'ดอนลาน' },
        { label: 'นาคู' },
        { label: 'กุฎี' },
        { label: 'ลำตะเคียน' },
        { label: 'โคกช้าง' },
        { label: 'จักราช' },
        { label: 'หนองน้ำใหญ่' },
        { label: 'ลาดชิด' },
        { label: 'หน้าโคก' },
        { label: 'บ้านใหญ่' },
    ].map(tambons => arrayConvert(tambons)),

    ภาชี: [
        { label: 'ภาชี' },
        { label: 'โคกม่วง' },
        { label: 'ระโสม' },
        { label: 'หนองน้ำใส' },
        { label: 'ดอนหญ้านาง' },
        { label: 'ไผ่ล้อม' },
        { label: 'กระจิว' },
        { label: 'พระแก้ว' },
    ].map(tambons => arrayConvert(tambons)),

    ลาดบัวหลวง: [
        { label: 'ลาดบัวหลวง' },
        { label: 'หลักชัย' },
        { label: 'สามเมือง' },
        { label: 'พระยาบันลือ' },
        { label: 'สิงหนาท' },
        { label: 'คู้สลอด' },
        { label: 'คลองพระยาบันลือ' },
    ].map(tambons => arrayConvert(tambons)),

    วังน้อย: [
        { label: 'ลำตาเสา' },
        { label: 'บ่อตาโล่' },
        { label: 'วังน้อย' },
        { label: 'ลำไทร' },
        { label: 'สนับทึบ' },
        { label: 'พยอม' },
        { label: 'หันตะเภา' },
        { label: 'วังจุฬา' },
        { label: 'ข้าวงาม' },
        { label: 'ชะแมบ' },
    ].map(tambons => arrayConvert(tambons)),

    เสนา: [
        { label: 'เสนา' },
        { label: 'บ้านแพน' },
        { label: 'เจ้าเจ็ด' },
        { label: 'สามกอ' },
        { label: 'บางนมโค' },
        { label: 'หัวเวียง' },
        { label: 'มารวิชัย' },
        { label: 'บ้านโพธิ์' },
        { label: 'รางจรเข้' },
        { label: 'บ้านกระทุ่ม' },
        { label: 'บ้านแถว' },
        { label: 'ชายนา' },
        { label: 'สามตุ่ม' },
        { label: 'ลาดงา' },
        { label: 'ดอนทอง' },
        { label: 'บ้านหลวง' },
        { label: 'เจ้าเสด็จ' },
    ].map(tambons => arrayConvert(tambons)),

    บางซ้าย: [
        { label: 'บางซ้าย' },
        { label: 'แก้วฟ้า' },
        { label: 'เต่าเล่า' },
        { label: 'ปลายกลัด' },
        { label: 'เทพมงคล' },
        { label: 'วังพัฒนา' },
    ].map(tambons => arrayConvert(tambons)),

    อุทัย: [
        { label: 'คานหาม' },
        { label: 'บ้านช้าง' },
        { label: 'สามบัณฑิต' },
        { label: 'บ้านหีบ' },
        { label: 'หนองไม้ซุง' },
        { label: 'อุทัย' },
        { label: 'เสนา' },
        { label: 'หนองน้ำส้ม' },
        { label: 'โพสาวหาญ' },
        { label: 'ธนู' },
        { label: 'ข้าวเม่า' },
    ].map(tambons => arrayConvert(tambons)),

    มหาราช: [
        { label: 'หัวไผ่' },
        { label: 'กะทุ่ม' },
        { label: 'มหาราช' },
        { label: 'น้ำเต้า' },
        { label: 'บางนา' },
        { label: 'โรงช้าง' },
        { label: 'เจ้าปลุก' },
        { label: 'พิตเพียน' },
        { label: 'บ้านนา' },
        { label: 'บ้านขวาง' },
        { label: 'ท่าตอ' },
        { label: 'บ้านใหม่' },
    ].map(tambons => arrayConvert(tambons)),

    บ้านแพรก: [
        { label: 'บ้านแพรก' },
        { label: 'บ้านใหม่' },
        { label: 'สำพะเนียง' },
        { label: 'คลองน้อย' },
        { label: 'สองห้อง' },
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------อ่างทอง-----------------------------------*/

    เมืองอ่างทอง: [
        { label: 'ตลาดหลวง' },
        { label: 'บางแก้ว' },
        { label: 'ศาลาแดง' },
        { label: 'ป่างิ้ว' },
        { label: 'บ้านแห' },
        { label: 'ตลาดกรวด' },
        { label: 'มหาดไทย' },
        { label: 'บ้านอิฐ' },
        { label: 'หัวไผ่' },
        { label: 'จำปาหล่อ' },
        { label: 'โพสะ' },
        { label: 'บ้านรี' },
        { label: 'คลองวัว' },
        { label: 'ย่านซื่อ' },
    ].map(tambons => arrayConvert(tambons)),

    ไชโย: [
        { label: 'จรเข้ร้อง' },
        { label: 'ไชยภูมิ' },
        { label: 'ชัยฤทธิ์' },
        { label: 'เทวราช' },
        { label: 'ราชสถิตย์' },
        { label: 'ไชโย' },
        { label: 'หลักฟ้า' },
        { label: 'ชะไว' },
        { label: 'ตรีณรงค์' },
    ].map(tambons => arrayConvert(tambons)),

    ป่าโมก: [
        { label: 'บางปลากด' },
        { label: 'ป่าโมก' },
        { label: 'สายทอง' },
        { label: 'โรงช้าง' },
        { label: 'บางเสด็จ' },
        { label: 'นรสิงห์' },
        { label: 'เอกราช' },
        { label: 'โผงเผง' },
    ].map(tambons => arrayConvert(tambons)),

    โพธิ์ทอง: [
        { label: 'อ่างแก้ว' },
        { label: 'อินทประมูล' },
        { label: 'บางพลับ' },
        { label: 'หนองแม่ไก่' },
        { label: 'รำมะสัก' },
        { label: 'บางระกำ' },
        { label: 'โพธิ์รังนก' },
        { label: 'องครักษ์' },
        { label: 'โคกพุทรา' },
        { label: 'ยางช้าย' },
        { label: 'บ่อแร่' },
        { label: 'ทางพระ' },
        { label: 'สามง่าม' },
        { label: 'บางเจ้าฉ่า' },
        { label: 'คำหยาด' },
    ].map(tambons => arrayConvert(tambons)),

    แสวงหา: [
        { label: 'แสวงหา' },
        { label: 'ศรีพราน' },
        { label: 'บ้านพราน' },
        { label: 'วังน้ำเย็น' },
        { label: 'สีบัวทอง' },
        { label: 'ห้วยไผ่' },
        { label: 'จำลอง' },
    ].map(tambons => arrayConvert(tambons)),

    วิเศษชัยชาญ: [
        { label: 'ไผ่จำศิล' },
        { label: 'ศาลเจ้าโรงทอง' },
        { label: 'ไผ่ดำพัฒนา' },
        { label: 'สาวร้องไห้' },
        { label: 'ท่าช้าง' },
        { label: 'ยี่ล้น' },
        { label: 'บางจัก' },
        { label: 'ห้วยคันแหลน' },
        { label: 'คลองขนาก' },
        { label: 'ไผ่วง' },
        { label: 'สี่ร้อย' },
        { label: 'ม่วงเตี้ย' },
        { label: 'หัวตะพาน' },
        { label: 'หลักแก้ว' },
        { label: 'ตลาดใหม่' },
    ].map(tambons => arrayConvert(tambons)),

    สามโก้: [
        { label: 'สามโก้' },
        { label: 'ราษฎรพัฒนา' },
        { label: 'อบทม' },
        { label: 'โพธิ์ม่วงพันธ์' },
        { label: 'มงคลธรรมนิมิต' },
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------ลพบุรี-----------------------------------*/

    เมืองลพบุรี: [
        { label: 'ทะเลชุบศร' },
        { label: 'ท่าหิน' },
        { label: 'กกโก' },
        { label: 'โก่งธนู' },
        { label: 'เขาพระงาม' },
        { label: 'เขาสามยอด' },
        { label: 'โคกกะเทียม' },
        { label: 'โคกลำพาน' },
        { label: 'โคกตูม' },
        { label: 'งิ้วราย' },
        { label: 'ดอนโพธิ์' },
        { label: 'ตะลุง' },
        { label: 'ท่าแค' },
        { label: 'ท่าศาลา' },
        { label: 'นิคมสร้างตนเอง' },
        { label: 'บางขันหมาก' },
        { label: 'บ้านข่อย' },
        { label: 'ท้ายตลาด' },
        { label: 'ป่าตาล' },
        { label: 'พรหมมาสตร์' },
        { label: 'โพธิ์เก้าต้น' },
        { label: 'โพธิ์ตรุ' },
        { label: 'สี่คลอง' },
        { label: 'ถนนใหญ่' },
    ].map(tambons => arrayConvert(tambons)),

    พัฒนานิคม: [
        { label: 'พัฒนานิคม' },
        { label: 'ช่องสาริกา' },
        { label: 'มะนาวหวาน' },
        { label: 'ดีลัง' },
        { label: 'โคกสลุง' },
        { label: 'ชอนน้อย' },
        { label: 'หนองบัว' },
        { label: 'ห้วยขุนราม' },
        { label: 'น้ำสุด' },
    ].map(tambons => arrayConvert(tambons)),

    โคกสำโรง: [
        { label: 'โคกสำโรง' },
        { label: 'เกาะแก้ว' },
        { label: 'ถลุงเหล็ก' },
        { label: 'หลุมข้าว' },
        { label: 'ห้วยโป่ง' },
        { label: 'คลองเกตุ' },
        { label: 'สะแกราบ' },
        { label: 'เพนียด' },
        { label: 'วังเพลิง' },
        { label: 'ดงมะรุม' },
        { label: 'วังขอนขว้าง' },
        { label: 'วังจั่น' },
        { label: 'หนองแขม' },
    ].map(tambons => arrayConvert(tambons)),

    ชัยบาดาล: [
        { label: 'ลำนารายณ์' },
        { label: 'ชัยนารายณ์' },
        { label: 'ศิลาทิพย์' },
        { label: 'ห้วยหิน' },
        { label: 'ม่วงค่อม' },
        { label: 'บัวชุม' },
        { label: 'ท่าดินดำ' },
        { label: 'มะกอกหวาน' },
        { label: 'ซับตะเคียน' },
        { label: 'นาโสม' },
        { label: 'หนองยายโต๊ะ' },
        { label: 'เกาะรัง' },
        { label: 'ท่ามะนาว' },
        { label: 'นิคมลำนารายณ์' },
        { label: 'ชัยบาดาล' },
        { label: 'บ้านใหม่สามัคคี' },
        { label: 'เขาแหลม' },
    ].map(tambons => arrayConvert(tambons)),

    ท่าวุ้ง: [
        { label: 'ท่าวุ้ง' },
        { label: 'บางคู้' },
        { label: 'โพตลาดแก้ว' },
        { label: 'บางลี่' },
        { label: 'บางงา' },
        { label: 'โคกสลุด' },
        { label: 'เขาสมอคอน' },
        { label: 'หัวสำโรง' },
        { label: 'ลาดสาลี่' },
        { label: 'บ้านเบิก' },
        { label: 'มุจลินท์' },
    ].map(tambons => arrayConvert(tambons)),

    บ้านหมี่: [
        { label: 'ไผ่ใหญ่' },
        { label: 'บ้านทราย' },
        { label: 'บ้านกล้วย' },
        { label: 'ดงพลับ' },
        { label: 'บ้านชี' },
        { label: 'พุคา' },
        { label: 'หินปัก' },
        { label: 'บางพึ่ง' },
        { label: 'หนองทรายขาว' },
        { label: 'บางกะพี้' },
        { label: 'หนองเต่า' },
        { label: 'โพนทอง' },
        { label: 'บางขาม' },
        { label: 'ดอนดึง' },
        { label: 'ชอนม่วง' },
        { label: 'หนองกระเบียน' },
        { label: 'สายห้วยแก้ว' },
        { label: 'มหาสอน' },
        { label: 'บ้านหมี่' },
        { label: 'เชียงงา' },
        { label: 'หนองเมือง' },
        { label: 'สนามแจง' },
    ].map(tambons => arrayConvert(tambons)),

    ท่าหลวง: [
        { label: 'ท่าหลวง' },
        { label: 'แก่งผักกูด' },
        { label: 'ซับจำปา' },
        { label: 'หนองผักแว่น' },
        { label: 'ทะเลวังวัด' },
        { label: 'หัวลำ' },
    ].map(tambons => arrayConvert(tambons)),

    สระโบสถ์: [
        { label: 'สระโบสถ์' },
        { label: 'มหาโพธิ' },
        { label: 'ทุ่งท่าช้าง' },
        { label: 'ห้วยใหญ่' },
        { label: 'นิยมชัย' },
    ].map(tambons => arrayConvert(tambons)),

    โคกเจริญ: [
        { label: 'โคกเจริญ' },
        { label: 'ยางราก' },
        { label: 'หนองมะค่า' },
        { label: 'วังทอง' },
        { label: 'โคกแสมสาร' },
    ].map(tambons => arrayConvert(tambons)),

    ลำสนธิ: [
        { label: 'ลำสนธิ' },
        { label: 'ซับสมบูรณ์' },
        { label: 'หนองรี' },
        { label: 'กุดตาเพชร' },
        { label: 'เขารวก' },
        { label: 'เขาน้อย' },
    ].map(tambons => arrayConvert(tambons)),

    หนองม่วง: [
        { label: 'หนองม่วง' },
        { label: 'บ่อทอง' },
        { label: 'ดงดินแดง' },
        { label: 'ชอนสมบูรณ์' },
        { label: 'ยางโทน' },
        { label: 'ชอนสารเดช' },
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------สิงห์บุรี-----------------------------------*/

    เมืองสิงห์บุรี: [
        { label: 'บางพุทรา' },
        { label: 'บางมัญ' },
        { label: 'โพกรวม' },
        { label: 'ม่วงหมู่' },
        { label: 'หัวไผ่' },
        { label: 'ต้นโพธิ์' },
        { label: 'จักรสีห์' },
        { label: 'บางกระบือ' },
    ].map(tambons => arrayConvert(tambons)),

    บางระจัน: [
        { label: 'สิงห์' },
        { label: 'ไม้ดัด' },
        { label: 'เชิงกลัด' },
        { label: 'โพชนไก่' },
        { label: 'แม่ลา' },
        { label: 'บ้านจ่า' },
        { label: 'พักทัน' },
        { label: 'สระแจง' },
    ].map(tambons => arrayConvert(tambons)),

    ค่ายบางระจัน: [
        { label: 'โพทะเล' },
        { label: 'บางระจัน' },
        { label: 'โพสังโฆ' },
        { label: 'ท่าข้าม' },
        { label: 'คอทราย' },
        { label: 'หนองกระทุ่ม' },
    ].map(tambons => arrayConvert(tambons)),

    พรหมบุรี: [
        { label: 'พระงาม' },
        { label: 'พรหมบุรี' },
        { label: 'บางน้ำเชี่ยว' },
        { label: 'บ้านหม้อ' },
        { label: 'บ้านแป้ง' },
        { label: 'หัวป่า' },
        { label: 'โรงช้าง' },
    ].map(tambons => arrayConvert(tambons)),

    ท่าช้าง: [
        { label: 'ถอนสมอ' },
        { label: 'โพประจักษ์' },
        { label: 'วิหารขาว' },
        { label: 'พิกุลทอง' },
    ].map(tambons => arrayConvert(tambons)),

    อินทร์บุรี: [
        { label: 'อินทร์บุรี' },
        { label: 'ประศุก' },
        { label: 'ทับยา' },
        { label: 'งิ้วราย' },
        { label: 'ชีน้ำร้าย' },
        { label: 'ท่างาม' },
        { label: 'น้ำตาล' },
        { label: 'ทองเอน' },
        { label: 'ห้วยชัน' },
        { label: 'โพธิ์ชัย' },
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------ชัยนาท-----------------------------------*/

    เมืองชัยนาท: [
        { label: 'ในเมือง' },
        { label: 'บ้านกล้วย' },
        { label: 'ท่าชัย' },
        { label: 'ชัยนาท' },
        { label: 'เขาท่าพระ' },
        { label: 'หาดท่าเสา' },
        { label: 'ธรรมามูล' },
        { label: 'เสือโฮก' },
        { label: 'นางลือ' },
    ].map(tambons => arrayConvert(tambons)),

    มโนรมย์: [
        { label: 'คุ้งสำเภา' },
        { label: 'วัดโคก' },
        { label: 'ศิลาดาน' },
        { label: 'ท่าฉนวน' },
        { label: 'หางน้ำสาคร' },
        { label: 'ไร่พัฒนา' },
        { label: 'อู่ตะเภา' },
    ].map(tambons => arrayConvert(tambons)),

    วัดสิงห์: [
        { label: 'วัดสิงห์' },
        { label: 'มะขามเฒ่า' },
        { label: 'หนองน้อย' },
        { label: 'หนองบัว' },
        { label: 'หนองขุ่น' },
        { label: 'บ่อแร่' },
        { label: 'วังหมัน' },
    ].map(tambons => arrayConvert(tambons)),

    สรรพยา: [
        { label: 'สรรพยา' },
        { label: 'ตลุก' },
        { label: 'เขาแก้ว' },
        { label: 'โพนางดำตก' },
        { label: 'โพนางดำออก' },
        { label: 'บางหลวง' },
        { label: 'หาดอาษา' },
    ].map(tambons => arrayConvert(tambons)),

    สรรคบุรี: [
        { label: 'แพรกศรีราชา' },
        { label: 'เที่ยงแท้' },
        { label: 'ห้วยกรด' },
        { label: 'โพงาม' },
        { label: 'บางขุด' },
        { label: 'ดงคอน' },
        { label: 'ดอนกำ' },
        { label: 'ห้วยกรดพัฒนา' },
    ].map(tambons => arrayConvert(tambons)),

    หันคา: [
        { label: 'หันคา' },
        { label: 'บ้านเชี่ยน' },
        { label: 'ไพรนกยูง' },
        { label: 'หนองแซง' },
        { label: 'ห้วยงู' },
        { label: 'วังไก่เถื่อน' },
        { label: 'เด่นใหญ่' },
        { label: 'สามง่ามท่าโบสถ์' },
    ].map(tambons => arrayConvert(tambons)),

    หนองมะโมง: [
        { label: 'หนองมะโมง' },
        { label: 'วังตะเคียน' },
        { label: 'สะพานหิน' },
        { label: 'กุดจอก' },
    ].map(tambons => arrayConvert(tambons)),

    เนินขาม: [
        { label: 'เนินขาม' },
        { label: 'กะบกเตี้ย' },
        { label: 'สุขเดือนห้า' },
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------สระบุรี-----------------------------------*/

    เมืองสระบุรี: [
        {label:'ปากเพรียว'},
        {label:'ดาวเรือง'},
        {label:'นาโฉง'},
        {label:'โคกสว่าง'},
        {label:'หนองโน'},
        {label:'หนองยาว'},
        {label:'ปากข้าวสาร'},
        {label:'หนองปลาไหล'},
        {label:'กุดนกเปล้า'},
        {label:'ตลิ่งชัน'},
        {label:'ตะกุด'},
    ].map(tambons => arrayConvert(tambons)),

    แก่งคอย: [
        {label:'แก่งคอย'},
        {label:'ทับกวาง'},
        {label:'ตาลเดี่ยว'},
        {label:'ห้วยแห้ง'},
        {label:'ท่าคล้อ'},
        {label:'หินซ้อน'},
        {label:'บ้านธาตุ'},
        {label:'บ้านป่า'},
        {label:'ท่าตูม'},
        {label:'ชะอม'},
        {label:'สองคอน'},
        {label:'เตาปูน'},
        {label:'ชำผักแพว'},
        {label:'ท่ามะปราง'},
    ].map(tambons => arrayConvert(tambons)),

    หนองแค: [
        {label:'หนองแค'},
        {label:'กุ่มหัก'},
        {label:'คชสิทธิ์'},
        {label:'โคกตูม'},
        {label:'โคกแย้'},
        {label:'บัวลอย'},
        {label:'ไผ่ต่ำ'},
        {label:'โพนทอง'},
        {label:'ห้วยขมิ้น'},
        {label:'ห้วยทราย'},
        {label:'หนองไข่น้ำ'},
        {label:'หนองแขม'},
        {label:'หนองจิก'},
        {label:'หนองจรเข้'},
        {label:'หนองนาก'},
        {label:'หนองปลาหมอ'},
        {label:'หนองปลิง'},
        {label:'หนองโรง'},
    ].map(tambons => arrayConvert(tambons)),

    วิหารแดง: [
        {label:'หนองหมู'},
        {label:'บ้านลำ'},
        {label:'คลองเรือ'},
        {label:'วิหารแดง'},
        {label:'หนองสรวง'},
        {label:'เจริญธรรม'},
    ].map(tambons => arrayConvert(tambons)),

    หนองแซง: [
        {label:'หนองแซง'},
        {label:'หนองควายโซ'},
        {label:'หนองหัวโพ'},
        {label:'หนองสีดา'},
        {label:'หนองกบ'},
        {label:'ไก่เส่า'},
        {label:'โคกสะอาด'},
        {label:'ม่วงหวาน'},
        {label:'เขาดิน'},
    ].map(tambons => arrayConvert(tambons)),

    บ้านหมอ: [
        {label:'บ้านหมอ'},
        {label:'บางโขมด'},
        {label:'สร่างโศก'},
        {label:'ตลาดน้อย'},
        {label:'หรเทพ'},
        {label:'โคกใหญ่'},
        {label:'ไผ่ขวาง'},
        {label:'บ้านครัว'},
        {label:'หนองบัว'},
    ].map(tambons => arrayConvert(tambons)),

    ดอนพุด: [
        {label:'ดอนพุด'},
        {label:'ไผ่หลิ่ว'},
        {label:'บ้านหลวง'},
        {label:'ดงตะงาว'},
    ].map(tambons => arrayConvert(tambons)),

    หนองโดน: [
        {label:'หนองโดน'},
        {label:'บ้านกลับ'},
        {label:'ดอนทอง'},
        {label:'บ้านโปร่ง'},
    ].map(tambons => arrayConvert(tambons)),

    พระพุทธบาท: [
        {label:'พระพุทธบาท'},
        {label:'ขุนโขลน'},
        {label:'ธารเกษม'},
        {label:'นายาว'},
        {label:'พุคำจาน'},
        {label:'เขาวง'},
        {label:'ห้วยป่าหวาย'},
        {label:'พุกร่าง'},
        {label:'หนองแก'},
    ].map(tambons => arrayConvert(tambons)),

    เสาไห้: [
        {label:'เสาไห้'},
        {label:'บ้านยาง'},
        {label:'หัวปลวก'},
        {label:'งิ้วงาม'},
        {label:'ศาลารีไทย'},
        {label:'ต้นตาล'},
        {label:'ท่าช้าง'},
        {label:'พระยาทด'},
        {label:'ม่วงงาม'},
        {label:'เริงราง'},
        {label:'เมืองเก่า'},
        {label:'สวนดอกไม้'},
    ].map(tambons => arrayConvert(tambons)),

    มวกเหล็ก: [
        {label:'มวกเหล็ก'},
        {label:'มิตรภาพ'},
        {label:'หนองย่างเสือ'},
        {label:'ลำสมพุง'},
        {label:'ลำพญากลาง'},
        {label:'ซับสนุ่น'},
    ].map(tambons => arrayConvert(tambons)),

    วังม่วง: [
        {label:'แสลงพัน'},
        {label:'คำพราน'},
        {label:'วังม่วง'},
    ].map(tambons => arrayConvert(tambons)),

    เฉลิมพระเกียรติ: [
        {label:'เขาดินพัฒนา'},
        {label:'บ้านแก้ง'},
        {label:'ผึ้งรวง'},
        {label:'พุแค'},
        {label:'ห้วยบง'},
        {label:'หน้าพระลาน'},
    ].map(tambons => arrayConvert(tambons)),

    /*-----------------------------------ชลบุรี-----------------------------------*/

    เมืองชลบุรี: [
        {label:'บางปลาสร้อย'},
        {label:'มะขามหย่ง'},
        {label:'บ้านโขด'},
        {label:'แสนสุข'},
        {label:'บ้านสวน'},
        {label:'หนองรี'},
        {label:'นาป่า'},
        {label:'หนองข้างคอก'},
        {label:'ดอนหัวฬ่อ'},
        {label:'หนองไม้แดง'},
        {label:'บางทราย'},
        {label:'คลองตำหรุ'},
        {label:'เหมือง'},
        {label:'บ้านปึก'},
        {label:'ห้วยกะปิ'},
        {label:'เสม็ด'},
        {label:'อ่างศิลา'},
        {label:'สำนักบก'},
    ].map(tambons => arrayConvert(tambons)),

    บ้านบึง:[
        {label:'บ้านบึง'},
        {label:'คลองกิ่ว'},
        {label:'มาบไผ่'},
        {label:'หนองซ้ำซาก'},
        {label:'หนองบอนแดง'},
        {label:'หนองชาก'},
        {label:'หนองอิรุณ'},
        {label:'หนองไผ่แก้ว'},
    ].map(tambons => arrayConvert(tambons)),

    หนองใหญ่: [
        {label:'หนองใหญ่'},
        {label:'คลองพลู'},
        {label:'หนองเสือช้าง'},
        {label:'ห้างสูง'},
        {label:'เขาซก'},
    ].map(tambons => arrayConvert(tambons)),

    บางละมุง: [
        {label:'บางละมุง'},
        {label:'หนองปรือ'},
        {label:'หนองปลาไหล'},
        {label:'โป่ง'},
        {label:'เขาไม้แก้ว'},
        {label:'ห้วยใหญ่'},
        {label:'ตะเคียนเตี้ย'},
        {label:'นาเกลือ'},
    ].map(tambons => arrayConvert(tambons)),

    พานทอง: [
        {label:'พานทอง'},
        {label:'หนองตำลึง'},
        {label:'มาบโป่ง'},
        {label:'หนองกะขะ'},
        {label:'หนองหงษ์'},
        {label:'โคกขี้หนอน'},
        {label:'บ้านเก่า'},
        {label:'หน้าประดู่'},
        {label:'บางนาง'},
        {label:'เกาะลอย'},
        {label:'บางหัก'},
    ].map(tambons => arrayConvert(tambons)),

    พนัสนิคม: [
        {label:'พนัสนิคม'},
        {label:'หน้าพระธาตุ'},
        {label:'วัดหลวง'},
        {label:'บ้านเซิด'},
        {label:'นาเริก'},
        {label:'หมอนนาง'},
        {label:'สระสี่เหลี่ยม'},
        {label:'วัดโบสถ์'},
        {label:'กุฎโง้ง'},
        {label:'หัวถนน'},
        {label:'ท่าข้าม'},
        {label:'หนองปรือ'},
        {label:'หนองขยาด'},
        {label:'ทุ่งขวาง'},
        {label:'หนองเหียง'},
        {label:'นาวังหิน'},
        {label:'บ้านช้าง'},
        {label:'โคกเพลาะ'},
        {label:'ไร่หลักทอง'},
        {label:'นามะตูม'},
    ].map(tambons => arrayConvert(tambons)),

    ศรีราชา: [
        {label:'ศรีราชา'},
        {label:'สุรศักดิ์'},
        {label:'ทุ่งสุขลา'},
        {label:'บึง'},
        {label:'หนองขาม'},
        {label:'เขาคันทรง'},
        {label:'บางพระ'},
        {label:'บ่อวิน'},
    ].map(tambons => arrayConvert(tambons)),

    เกาะสีชัง: [
        {label:'ท่าเทววงษ์'},
    ].map(tambons => arrayConvert(tambons)),

    สัตหีบ: [
        {label :'สัตหีบ'},
        {label :'นาจอมเทียน'},
        {label :'พลูตาหลวง'},
        {label :'บางเสร่'},
        {label :'แสมสาร'},
    ].map(tambons => arrayConvert(tambons)),

    บ่อทอง: [
        {label:'บ่อทอง'},
        {label:'วัดสุวรรณ'},
        {label:'บ่อกวางทอง'},
        {label:'ธาตุทอง'},
        {label:'เกษตรสุวรรณ'},
        {label:'พลวงทอง'},
    ].map(tambons => arrayConvert(tambons)),

    เกาะจันทร์: [
        {label:'เกาะจันทร์'},
        {label:'ท่าบุญมี'},
    ].map(tambons => arrayConvert(tambons)),

}