function arrayConvert(value) {
    return {
        value: value.label,
        label: value.label,
    }
}
export const provinces = [
    { label: 'กรุงเทพมหานคร' },
    { label: 'สมุทรปราการ' },
    { label: 'นนทบุรี' },
    { label: 'ปทุมธานี' },
    { label: 'พระนครศรีอยุธยา' },
    { label: 'อ่างทอง' },
    { label: 'ลพบุรี' },
    { label: 'สิงห์บุรี' },
    { label: 'ชัยนาท' },
    { label: 'สระบุรี' },
    { label: 'ชลบุรี' },
    { label: 'ระยอง' },
    { label: 'จันทบุรี' },
    { label: 'ตราด' },
    { label: 'ฉะเชิงเทรา' },
    { label: 'ปราจีนบุรี' },
    { label: 'นครนายก' },
    { label: 'สระแก้ว' },
    { label: 'นครราชสีมา' },
    { label: 'บุรีรัมย์' },
    { label: 'สุรินทร์' },
    { label: 'ศรีสะเกษ' },
    { label: 'อุบลราชธานี' },
    { label: 'ยโสธร' },
    { label: 'ชัยภูมิ' },
    { label: 'อำนาจเจริญ' },
    { label: 'บึงกาฬ' },
    { label: 'หนองบัวลำภู' },
    { label: 'ขอนแก่น' },
    { label: 'อุดรธานี' },
    { label: 'เลย' },
    { label: 'หนองคาย' },
    { label: 'มหาสารคาม' },
    { label: 'ร้อยเอ็ด' },
    { label: 'กาฬสินธุ์' },
    { label: 'สกลนคร' },
    { label: 'นครพนม' },
    { label: 'มุกดาหาร' },
    { label: 'เชียงใหม่' },
    { label: 'ลำพูน' },
    { label: 'ลำปาง' },
    { label: 'อุตรดิตถ์' },
    { label: 'แพร่' },
    { label: 'น่าน' },
    { label: 'พะเยา' },
    { label: 'เชียงราย' },
    { label: 'แม่ฮ่องสอน' },
    { label: 'นครสวรรค์' },
    { label: 'อุทัยธานี' },
    { label: 'กำแพงเพชร' },
    { label: 'ตาก' },
    { label: 'สุโขทัย' },
    { label: 'พิษณุโลก' },
    { label: 'พิจิตร' },
    { label: 'เพชรบูรณ์' },
    { label: 'ราชบุรี' },
    { label: 'กาญจนบุรี' },
    { label: 'สุพรรณบุรี' },
    { label: 'นครปฐม' },
    { label: 'สมุทรสาคร' },
    { label: 'สมุทรสงคราม' },
    { label: 'เพชรบุรี' },
    { label: 'ประจวบคีรีขันธ์' },
    { label: 'นครศรีธรรมราช' },
    { label: 'กระบี่' },
    { label: 'พังงา' },
    { label: 'ภูเก็ต' },
    { label: 'สุราษฎร์ธานี' },
    { label: 'ระนอง' },
    { label: 'ชุมพร' },
    { label: 'สงขลา' },
    { label: 'สตูล' },
    { label: 'ตรัง' },
    { label: 'พัทลุง' },
    { label: 'ปัตตานี' },
    { label: 'ยะลา' },
    { label: 'นราธิวาส' },
]
    .map(province => arrayConvert(province))
export const amphoes = {
    กรุงเทพมหานคร: [
        { label: 'พระนคร' },
        { label: 'ดุสิต' },
        { label: 'หนองจอก' },
        { label: 'บางรัก' },
        { label: 'บางเขน' },
        { label: 'บางกะปิ' },
        { label: 'ปทุมวัน' },
        { label: 'ป้อมปราบศัตรูพ่าย' },
        { label: 'พระโขนง' },
        { label: 'มีนบุรี' },
        { label: 'ลาดกระบัง' },
        { label: 'ยานนาวา' },
    ].map(amphoe => arrayConvert(amphoe)),

}
export const tambons = {
    พระนคร: [

    ].map(amphoe => arrayConvert(amphoe)),
}