const SORT_BY_NEWEST = 'SORT_BY_NEWEST'
const SORT_BY_LATEST = 'SORT_BY_LATEST'
const SHOW_ALL = 'SHOW_ALL'
const SHOW_COMPLETE = 'SHOW_COMPLETE'
const SHOW_ACTIVATE = 'SHOW_ACTIVATE'

export { SORT_BY_NEWEST, SORT_BY_LATEST, SHOW_ALL, SHOW_COMPLETE, SHOW_ACTIVATE }